<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <Version>12.2.0</Version>
    <Description>IndexedDB storage provider for WitDatabase. Enables running WitDatabase entirely in the browser with Blazor WebAssembly applications.</Description>
    <PackageTags>OutWit;database;indexeddb;blazor;wasm;webassembly;storage;browser;client-side</PackageTags>
  </PropertyGroup>

  <!-- Blazor WASM support -->
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.JSInterop" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OutWit.Database.Core\OutWit.Database.Core.csproj" />
  </ItemGroup>

</Project>
