using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Text;
using System.Windows.Input;
using Microsoft.Extensions.Logging;
using OutWit.Common.Aspects;
using OutWit.Common.Locker;
using OutWit.Common.MVVM.Commands;
using OutWit.Common.MVVM.ViewModels;
using OutWit.Common.Utils;
using OutWit.Database.Studio.Converters;
using OutWit.Database.Studio.Models;
using OutWit.Database.Studio.Services;

namespace OutWit.Database.Studio.ViewModels;

/// <summary>
/// ViewModel for the Table Editor feature.
/// Allows browsing, editing, adding, and deleting table data.
/// </summary>
public class TableEditorViewModel : ViewModelBase<ApplicationViewModel>
{
    #region Constants

    private const int DEFAULT_PAGE_SIZE = 1000;

    #endregion

    #region Fields

    private DataTable? m_originalData;
    private readonly HashSet<DataRow> m_deletedRows = [];
    private readonly HashSet<DataRow> m_modifiedRows = [];
    private readonly List<DataRow> m_newRows = [];

    #endregion

    #region Constructors

    public TableEditorViewModel(ApplicationViewModel applicationVm)
        : base(applicationVm)
    {
        InitDefault();
        InitEvents();
        InitCommands();
    }

    #endregion

    #region Initialization

    private void InitDefault()
    {
        Columns = [];
        PageSize = DEFAULT_PAGE_SIZE;
    }

    private void InitEvents()
    {
        PropertyChanged += OnPropertyChanged;
        Database.ConnectionStatusChanged += OnConnectionStatusChanged;
    }

    private void InitCommands()
    {
        LoadDataCommand = new RelayCommandAsync(LoadDataAsync);
        RefreshCommand = new RelayCommandAsync(RefreshDataAsync);
        AddRowCommand = new RelayCommand(AddRow);
        DeleteRowCommand = new RelayCommand(DeleteSelectedRow);
        CommitCommand = new RelayCommandAsync(CommitChangesAsync);
        RollbackCommand = new RelayCommand(RollbackChanges);
    }

    #endregion

    #region Functions

    /// <summary>
    /// Loads data for the specified table.
    /// </summary>
    public async Task LoadTableAsync(string tableName)
    {
        using var locker = GlobalLocker.Lock(nameof(TableEditorViewModel));

        TableName = tableName;
        await LoadColumnsAsync();
        await LoadDataAsync();
    }

    private async Task LoadColumnsAsync()
    {
        if (string.IsNullOrWhiteSpace(TableName) || !Database.IsConnected)
            return;

        try
        {
            var columns = await Database.GetColumnsAsync(TableName);
            Columns = columns.ToList();
            PrimaryKeyColumns = columns.Where(c => c.IsPrimaryKey).Select(c => c.Name).ToList();
        }
        catch (Exception ex)
        {
            ErrorMessage = $"Failed to load columns: {ex.Message}";
            Logger.LogError(ex, "Failed to load columns for table {TableName}", TableName);
        }
    }

    private async Task LoadDataAsync()
    {
        if (string.IsNullOrWhiteSpace(TableName) || !Database.IsConnected)
            return;

        IsLoading = true;
        ErrorMessage = null;
        ClearChangeTracking();

        try
        {
            var sql = $"SELECT * FROM [{SqlValueFormatter.EscapeIdentifier(TableName)}] LIMIT {PageSize}";
            var result = await Database.ExecuteQueryAsync(sql);

            if (!string.IsNullOrEmpty(result.ErrorMessage))
            {
                ErrorMessage = result.ErrorMessage;
                return;
            }

            m_originalData = result.Data?.Copy();
            EditableData = result.Data;
            
            if (EditableData != null)
            {
                CurrentView = new DataView(EditableData);
                TotalRowCount = EditableData.Rows.Count;
            }

            ApplicationVm.MainWindowVm.StatusText = $"Loaded {TotalRowCount} rows from table \"{TableName}\"";
            Logger.LogInformation("Loaded {Count} rows from table {TableName}", TotalRowCount, TableName);
        }
        catch (Exception ex)
        {
            ErrorMessage = $"Failed to load data: {ex.Message}";
            Logger.LogError(ex, "Failed to load data from table {TableName}", TableName);
        }
        finally
        {
            IsLoading = false;
            UpdateStatus();
        }
    }

    private async Task RefreshDataAsync()
    {
        if (HasChanges)
        {
            // In a real app, we would show a confirmation dialog
            // For now, just reload and discard changes
        }

        await LoadDataAsync();
    }

    private void AddRow()
    {
        if (EditableData == null || Columns.Count == 0)
            return;

        var newRow = EditableData.NewRow();

        // Set default values for columns (skip auto-increment - they'll be generated by DB)
        foreach (var column in Columns)
        {
            // Skip auto-increment columns - database will generate value
            if (column.IsAutoIncrement)
            {
                newRow[column.Name] = DBNull.Value;
                continue;
            }
            
            if (!string.IsNullOrEmpty(column.DefaultValue))
            {
                try
                {
                    var defaultValue = ParseDefaultValue(column.DefaultValue, EditableData.Columns[column.Name].DataType);
                    newRow[column.Name] = defaultValue ?? DBNull.Value;
                }
                catch
                {
                    newRow[column.Name] = DBNull.Value;
                }
            }
            else if (column.IsNullable)
            {
                newRow[column.Name] = DBNull.Value;
            }
        }

        EditableData.Rows.Add(newRow);
        m_newRows.Add(newRow);
        TotalRowCount = EditableData.Rows.Count;
        
        // Force CurrentView to refresh
        CurrentView = new DataView(EditableData);
        
        UpdateStatus();
        
        Logger.LogDebug("Added new row. Total rows: {Count}, New rows: {NewCount}", TotalRowCount, m_newRows.Count);
    }

    private void DeleteSelectedRow()
    {
        if (SelectedRowView == null || EditableData == null)
            return;

        var row = SelectedRowView.Row;
        
        if (m_newRows.Contains(row))
        {
            // Remove new row that hasn't been committed yet
            m_newRows.Remove(row);
            EditableData.Rows.Remove(row);
        }
        else
        {
            // Mark existing row for deletion
            m_deletedRows.Add(row);
            row.Delete();
        }

        TotalRowCount = EditableData.Rows.Count - m_deletedRows.Count;
        SelectedRowView = null;
        
        UpdateStatus();
    }

    private async Task CommitChangesAsync()
    {
        if (EditableData == null || string.IsNullOrWhiteSpace(TableName) || m_originalData == null)
            return;

        IsLoading = true;
        ErrorMessage = null;

        try
        {
            var errors = new List<string>();

            // Process deletions
            foreach (var row in m_deletedRows)
            {
                // Find the original row by matching with m_originalData
                var originalRowIndex = FindOriginalRowIndex(row);
                if (originalRowIndex < 0)
                {
                    errors.Add("Cannot delete row: original row not found");
                    continue;
                }

                var originalRow = m_originalData.Rows[originalRowIndex];
                var whereClause = BuildWhereClause(originalRow);
                
                if (string.IsNullOrEmpty(whereClause))
                {
                    errors.Add("Cannot delete row: no primary key or unique identifier");
                    continue;
                }

                var deleteSql = $"DELETE FROM [{SqlValueFormatter.EscapeIdentifier(TableName)}] WHERE {whereClause}";
                Logger.LogDebug("Executing DELETE: {Sql}", deleteSql);
                
                try
                {
                    await Database.ExecuteNonQueryAsync(deleteSql);
                }
                catch (Exception ex)
                {
                    errors.Add($"Delete failed: {ex.Message}");
                }
            }

            // Process new rows
            foreach (var newRow in m_newRows)
            {
                var insertSql = BuildInsertStatement(newRow);
                Logger.LogDebug("Executing INSERT: {Sql}", insertSql);
                
                try
                {
                    await Database.ExecuteNonQueryAsync(insertSql);
                }
                catch (Exception ex)
                {
                    errors.Add($"Insert failed: {ex.Message}");
                }
            }

            // Process modifications
            foreach (var modifiedRow in m_modifiedRows)
            {
                if (modifiedRow.RowState == DataRowState.Deleted || modifiedRow.RowState == DataRowState.Detached)
                    continue;

                // Find original row to build WHERE clause
                var originalRowIndex = FindOriginalRowIndex(modifiedRow);
                if (originalRowIndex < 0)
                {
                    errors.Add("Cannot update row: original row not found");
                    continue;
                }

                var originalRow = m_originalData.Rows[originalRowIndex];
                var whereClause = BuildWhereClause(originalRow);
                
                if (string.IsNullOrEmpty(whereClause))
                {
                    errors.Add("Cannot update row: no primary key or unique identifier");
                    continue;
                }

                var updateSql = BuildUpdateStatement(modifiedRow, whereClause);
                Logger.LogDebug("Executing UPDATE: {Sql}", updateSql);
                
                try
                {
                    var rowsAffected = await Database.ExecuteNonQueryAsync(updateSql);
                    Logger.LogDebug("UPDATE affected {Rows} rows", rowsAffected);
                }
                catch (Exception ex)
                {
                    errors.Add($"Update failed: {ex.Message}");
                }
            }

            if (errors.Count > 0)
            {
                ErrorMessage = string.Join("\n", errors);
            }
            else
            {
                ApplicationVm.MainWindowVm.StatusText = "Changes committed successfully";
            }

            // Reload data to reflect actual database state
            await LoadDataAsync();
        }
        catch (Exception ex)
        {
            ErrorMessage = $"Commit failed: {ex.Message}";
            Logger.LogError(ex, "Failed to commit changes to table {TableName}", TableName);
        }
        finally
        {
            IsLoading = false;
            UpdateStatus();
        }
    }

    /// <summary>
    /// Finds the index of the row in original data by matching primary key or all columns.
    /// </summary>
    private int FindOriginalRowIndex(DataRow row)
    {
        if (m_originalData == null)
            return -1;

        // If we have primary keys, use them to find the row
        if (PrimaryKeyColumns.Count > 0)
        {
            for (int i = 0; i < m_originalData.Rows.Count; i++)
            {
                var originalRow = m_originalData.Rows[i];
                bool match = true;
                
                foreach (var pkCol in PrimaryKeyColumns)
                {
                    // Handle deleted rows - they still have original values
                    var currentValue = row.RowState == DataRowState.Deleted 
                        ? row[pkCol, DataRowVersion.Original] 
                        : row[pkCol];
                    var originalValue = originalRow[pkCol];
                    
                    if (!Equals(currentValue, originalValue))
                    {
                        match = false;
                        break;
                    }
                }
                
                if (match)
                    return i;
            }
        }

        // Fallback: try to find by object reference position
        if (EditableData != null)
        {
            var currentIndex = EditableData.Rows.IndexOf(row);
            if (currentIndex >= 0 && currentIndex < m_originalData.Rows.Count)
                return currentIndex;
        }

        return -1;
    }

    private void RollbackChanges()
    {
        if (m_originalData == null || EditableData == null)
            return;

        ClearChangeTracking();

        // Restore original data
        EditableData.Clear();
        foreach (DataRow row in m_originalData.Rows)
        {
            EditableData.ImportRow(row);
        }

        CurrentView = new DataView(EditableData);
        TotalRowCount = EditableData.Rows.Count;

        ApplicationVm.MainWindowVm.StatusText = "Changes discarded";
        UpdateStatus();
    }

    private void ClearChangeTracking()
    {
        m_deletedRows.Clear();
        m_modifiedRows.Clear();
        m_newRows.Clear();
    }

    /// <summary>
    /// Called when a cell value is edited in the DataGrid.
    /// </summary>
    public void OnCellEdited(DataRowView rowView)
    {
        if (EditableData == null)
            return;

        var row = rowView.Row;
        
        // Don't track new rows as modified - they'll be inserted
        if (!m_newRows.Contains(row))
        {
            m_modifiedRows.Add(row);
            Logger.LogDebug("Row marked as modified. Total modified: {Count}", m_modifiedRows.Count);
        }

        UpdateStatus();
    }

    /// <summary>
    /// Clears the editor state.
    /// </summary>
    public void Clear()
    {
        using var locker = GlobalLocker.Lock(nameof(TableEditorViewModel));

        TableName = null;
        EditableData?.Dispose();
        EditableData = null;
        m_originalData?.Dispose();
        m_originalData = null;
        CurrentView = null;
        Columns = [];
        PrimaryKeyColumns = [];
        TotalRowCount = 0;
        ErrorMessage = null;
        SelectedRowView = null;
        ClearChangeTracking();
        UpdateStatus();
    }

    #endregion

    #region SQL Building

    private string BuildWhereClause(DataRow row)
    {
        var conditions = new List<string>();

        // Use primary key columns if available
        if (PrimaryKeyColumns.Count > 0)
        {
            foreach (var pkColumn in PrimaryKeyColumns)
            {
                var value = row[pkColumn];
                conditions.Add($"[{SqlValueFormatter.EscapeIdentifier(pkColumn)}] = {SqlValueFormatter.FormatForSql(value)}");
            }
        }
        else
        {
            // Fallback: use all columns (not ideal but works for simple cases)
            foreach (DataColumn col in row.Table.Columns)
            {
                var value = row[col];
                if (value == DBNull.Value)
                    conditions.Add($"[{SqlValueFormatter.EscapeIdentifier(col.ColumnName)}] IS NULL");
                else
                    conditions.Add($"[{SqlValueFormatter.EscapeIdentifier(col.ColumnName)}] = {SqlValueFormatter.FormatForSql(value)}");
            }
        }

        return string.Join(" AND ", conditions);
    }

    private string BuildInsertStatement(DataRow row)
    {
        var columns = new List<string>();
        var values = new List<string>();

        foreach (DataColumn col in row.Table.Columns)
        {
            var value = row[col];
            
            // Skip auto-increment columns with null/default values
            var columnInfo = Columns.FirstOrDefault(c => c.Name == col.ColumnName);
            if (columnInfo?.IsAutoIncrement == true && (value == DBNull.Value || value == null))
                continue;

            columns.Add($"[{SqlValueFormatter.EscapeIdentifier(col.ColumnName)}]");
            values.Add(SqlValueFormatter.FormatForSql(value));
        }

        return $"INSERT INTO [{SqlValueFormatter.EscapeIdentifier(TableName!)}] ({string.Join(", ", columns)}) VALUES ({string.Join(", ", values)})";
    }

    private string BuildUpdateStatement(DataRow row, string whereClause)
    {
        var setClauses = new List<string>();

        foreach (DataColumn col in row.Table.Columns)
        {
            // Skip primary key columns in SET clause
            if (PrimaryKeyColumns.Contains(col.ColumnName))
                continue;

            var value = row[col];
            setClauses.Add($"[{SqlValueFormatter.EscapeIdentifier(col.ColumnName)}] = {SqlValueFormatter.FormatForSql(value)}");
        }

        return $"UPDATE [{SqlValueFormatter.EscapeIdentifier(TableName!)}] SET {string.Join(", ", setClauses)} WHERE {whereClause}";
    }

    private static object? ParseDefaultValue(string defaultValue, Type targetType)
    {
        // Handle special SQL keywords
        var upper = defaultValue.Trim().ToUpperInvariant();
        
        if (upper is "NULL")
            return null;
        
        if (upper is "NOW()" or "CURRENT_TIMESTAMP" or "CURRENT_DATE" or "CURRENT_TIME")
            return DateTime.UtcNow;

        if (upper is "NEWGUID()" or "NEWUUID()")
            return Guid.NewGuid();

        if (upper is "TRUE")
            return true;

        if (upper is "FALSE")
            return false;

        // Try to convert the value
        try
        {
            return Convert.ChangeType(defaultValue.Trim('\'', '"'), targetType);
        }
        catch
        {
            return null;
        }
    }

    #endregion

    #region Tools

    private void UpdateStatus()
    {
        HasChanges = m_deletedRows.Count > 0 || m_modifiedRows.Count > 0 || m_newRows.Count > 0;
        CanCommit = HasChanges && !IsLoading;
        CanRollback = HasChanges && !IsLoading;
        CanAddRow = !string.IsNullOrWhiteSpace(TableName) && !IsLoading && Database.IsConnected;
        CanDeleteRow = SelectedRowView != null && !IsLoading;
        CanRefresh = !string.IsNullOrWhiteSpace(TableName) && !IsLoading && Database.IsConnected;
    }

    #endregion

    #region Event Handlers

    private void OnPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (GlobalLocker.IsLocked(nameof(TableEditorViewModel)))
            return;

        if (e.IsProperty((TableEditorViewModel vm) => vm.SelectedRowView))
            UpdateStatus();

        if (e.IsProperty((TableEditorViewModel vm) => vm.IsLoading))
            UpdateStatus();

        if (e.IsProperty((TableEditorViewModel vm) => vm.TableName))
            UpdateStatus();
    }

    private void OnConnectionStatusChanged(object? sender, bool isConnected)
    {
        if (!isConnected)
            Clear();

        UpdateStatus();
    }

    #endregion

    #region Properties

    /// <summary>
    /// Name of the currently loaded table.
    /// </summary>
    [Notify]
    public string? TableName { get; set; }

    /// <summary>
    /// Column definitions for the current table.
    /// </summary>
    [Notify]
    public List<ColumnInfo> Columns { get; set; } = null!;

    /// <summary>
    /// Names of primary key columns.
    /// </summary>
    [Notify]
    public List<string> PrimaryKeyColumns { get; set; } = null!;

    /// <summary>
    /// The editable data table.
    /// </summary>
    [Notify]
    public DataTable? EditableData { get; set; }

    /// <summary>
    /// Current view for display with sorting support.
    /// </summary>
    [Notify]
    public DataView? CurrentView { get; set; }

    /// <summary>
    /// Currently selected row in the grid.
    /// </summary>
    [Notify]
    public DataRowView? SelectedRowView { get; set; }

    /// <summary>
    /// Total number of rows.
    /// </summary>
    [Notify]
    public int TotalRowCount { get; set; }

    /// <summary>
    /// Page size for data loading.
    /// </summary>
    [Notify]
    public int PageSize { get; set; }

    /// <summary>
    /// Indicates if data is being loaded.
    /// </summary>
    [Notify]
    public bool IsLoading { get; set; }

    /// <summary>
    /// Error message if any operation failed.
    /// </summary>
    [Notify]
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Indicates if there are uncommitted changes.
    /// </summary>
    [Notify]
    public bool HasChanges { get; private set; }

    /// <summary>
    /// Indicates if changes can be committed.
    /// </summary>
    [Notify]
    public bool CanCommit { get; private set; }

    /// <summary>
    /// Indicates if changes can be rolled back.
    /// </summary>
    [Notify]
    public bool CanRollback { get; private set; }

    /// <summary>
    /// Indicates if a new row can be added.
    /// </summary>
    [Notify]
    public bool CanAddRow { get; private set; }

    /// <summary>
    /// Indicates if the selected row can be deleted.
    /// </summary>
    [Notify]
    public bool CanDeleteRow { get; private set; }

    /// <summary>
    /// Indicates if data can be refreshed.
    /// </summary>
    [Notify]
    public bool CanRefresh { get; private set; }

    #endregion

    #region Commands

    public ICommand LoadDataCommand { get; private set; } = null!;

    public ICommand RefreshCommand { get; private set; } = null!;

    public ICommand AddRowCommand { get; private set; } = null!;

    public ICommand DeleteRowCommand { get; private set; } = null!;

    public ICommand CommitCommand { get; private set; } = null!;

    public ICommand RollbackCommand { get; private set; } = null!;

    #endregion

    #region Services

    private IDatabaseService Database => ApplicationVm.Database;

    private ILogger<ApplicationViewModel> Logger => ApplicationVm.Logger;

    #endregion
}
