using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Logging;

namespace OutWit.Database.EntityFramework.Metadata;

/// <summary>
/// Validates an <see cref="IModel"/> for WitDatabase compatibility.
/// </summary>
public sealed class WitModelValidator : RelationalModelValidator
{
    #region Constants

    /// <summary>
    /// The only schema supported by WitDatabase.
    /// </summary>
    private const string SUPPORTED_SCHEMA = "public";

    #endregion

    #region Constructors

    /// <summary>
    /// Initializes a new instance of the <see cref="WitModelValidator"/> class.
    /// </summary>
    /// <param name="dependencies">The model validator dependencies.</param>
    /// <param name="relationalDependencies">The relational model validator dependencies.</param>
    public WitModelValidator(
        ModelValidatorDependencies dependencies,
        RelationalModelValidatorDependencies relationalDependencies)
        : base(dependencies, relationalDependencies)
    {
    }

    #endregion

    #region Validation

    /// <inheritdoc />
    public override void Validate(IModel model, IDiagnosticsLogger<DbLoggerCategory.Model.Validation> logger)
    {
        base.Validate(model, logger);

        ValidateSchemas(model);
        WarnAboutGeneratedValuesInCompositeKeys(model, logger);
    }

    /// <summary>
    /// Warns when a composite key contains a property the store is expected to generate.
    ///
    /// Value generation is tied to the row counter, which can only stand behind a key of one
    /// column, so such a key cannot be filled by the store. Said nothing about, the model is
    /// accepted, the emitted DDL declares the column NOT NULL with nothing to fill it, and the
    /// first insert that relies on generation fails with a NOT NULL violation naming a column the
    /// caller never mentioned - a data error for what is a modelling mistake.
    ///
    /// It is a warning and not an error on purpose. Such a model is perfectly usable as long as the
    /// caller supplies the values, and EF Core's SQLite provider accepts it too: run EF Core's own
    /// CompositeKeyEndToEnd suite against SQLite and two of its three tests pass. Refusing the model
    /// outright - which this check did when it was first written - breaks those two, and a provider
    /// that rejects what SQLite accepts is not a drop-in one.
    ///
    /// The common way to arrive here is an owned collection: EF gives it a composite key of
    /// (owner key, generated ordinal) unless told otherwise.
    /// </summary>
    private static void WarnAboutGeneratedValuesInCompositeKeys(
        IModel model,
        IDiagnosticsLogger<DbLoggerCategory.Model.Validation> logger)
    {
        foreach (var entityType in model.GetEntityTypes())
        {
            foreach (var key in entityType.GetKeys())
            {
                if (key.Properties.Count < 2)
                    continue;

                var generated = key.Properties
                    .Where(property => property.ValueGenerated != ValueGenerated.Never)
                    .ToList();

                if (generated.Count == 0)
                    continue;

                var keyColumns = string.Join(", ", key.Properties.Select(p => $"'{p.Name}'"));
                var generatedColumns = string.Join(", ", generated.Select(p => $"'{p.Name}'"));

                logger.Logger.LogWarning(
                    "WitDatabase cannot generate values inside a composite key. The entity type "
                    + "'{EntityType}' has key ({KeyColumns}), of which {GeneratedColumns} is "
                    + "configured to be generated by the store, and nothing will fill it - an "
                    + "insert that leaves it out fails on the NOT NULL constraint. Supply the "
                    + "value in your code and mark the property ValueGeneratedNever(), or "
                    + "configure a different key. An owned collection reaches this by default: its "
                    + "key is the owner's key plus a generated ordinal unless you configure one "
                    + "with HasKey.",
                    entityType.DisplayName(),
                    keyColumns,
                    generatedColumns);
            }
        }
    }

    /// <summary>
    /// Validates that no custom schemas are used (WitDatabase only supports the default 'public' schema).
    /// </summary>
    private static void ValidateSchemas(IModel model)
    {
        foreach (var entityType in model.GetEntityTypes())
        {
            var schema = entityType.GetSchema();
            if (schema != null && 
                !string.Equals(schema, SUPPORTED_SCHEMA, StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidOperationException(
                    $"WitDatabase does not support custom schemas. Entity '{entityType.DisplayName()}' " +
                    $"uses schema '{schema}', but only the default schema is supported. " +
                    $"Remove the schema specification or use 'public'.");
            }
        }
    }

    #endregion
}
