 using OutWit.Database.Definitions;
using OutWit.Database.Expressions;
using OutWit.Database.Parser.Expressions;
using OutWit.Database.Parser.Schema.Clauses;
using OutWit.Database.Parser.Schema.Types;
using OutWit.Database.Parser.Statements;
using OutWit.Database.Sql;
using OutWit.Database.Types;
using OutWit.Database.Values;

namespace OutWit.Database.Statements;

/// <summary>
/// INSERT statement execution including conflict resolution (UPSERT).
/// </summary>
public sealed partial class StatementExecutor
{
    #region INSERT

    private WitSqlResult ExecuteInsert(WitSqlStatementInsert insert)
    {
        var table = m_context.Database.GetTable(insert.TableName)
            ?? throw new InvalidOperationException($"Table '{insert.TableName}' not found");

        int rowsAffected = 0;
        long lastRowId = 0;
        List<WitSqlRow>? returningRows = null;

        if (insert.ReturningClause != null)
        {
            returningRows = [];
        }

        // Determine if we need conflict checking at all
        var needsConflictCheck = insert.ConflictResolution != ConflictResolutionType.None 
                                 || insert.OnConflict != null;

        // Determine which columns have auto-generated values (not explicitly specified)
        // This is used to skip UNIQUE validation for auto-increment PK when not explicitly set
        var explicitlySetColumns = insert.ColumnNames != null 
            ? new HashSet<string>(insert.ColumnNames, StringComparer.OrdinalIgnoreCase)
            : null; // null means positional - need to calculate per row

        if (insert.Values != null)
        {
            foreach (var valueRow in insert.Values)
            {
                var (row, rowId, autoGeneratedPkColumns) = BuildInsertRowWithAutoGenInfo(
                    table, insert.ColumnNames, valueRow, explicitlySetColumns);

                // Handle conflict resolution only if needed
                if (needsConflictCheck)
                {
                    var conflictResult = HandleConflictResolution(insert, table, ref row, ref rowId);
                    if (conflictResult == ConflictResult.Skip)
                        continue;
                    if (conflictResult == ConflictResult.Updated)
                    {
                        rowsAffected++;
                        if (returningRows != null)
                        {
                            var returningRow = BuildReturningRow(row, insert.ReturningClause!, table);
                            returningRows.Add(returningRow);
                        }
                        continue;
                    }
                }

                // Fire BEFORE INSERT triggers
                WitSqlRow? newRow = row;
                if (!FireTriggers(insert.TableName, TriggerEvent.Insert, TriggerTime.Before, null, ref newRow))
                    continue;

                row = newRow!.Value;

                // Check for INSTEAD OF triggers
                WitSqlRow? insteadOfRow = row;
                if (FireInsteadOfTrigger(insert.TableName, TriggerEvent.Insert, null, ref insteadOfRow))
                {
                    rowsAffected++;
                    continue;
                }

                // Pass auto-generated columns to skip their UNIQUE validation
                ValidateConstraintsWithAutoGen(table, row, insert.TableName, autoGeneratedPkColumns);
                m_context.Database.InsertRow(insert.TableName, row);
                lastRowId = rowId;
                rowsAffected++;

                if (returningRows != null)
                {
                    var returningRow = BuildReturningRow(row, insert.ReturningClause!, table);
                    returningRows.Add(returningRow);
                }

                // Fire AFTER INSERT triggers
                WitSqlRow? afterRow = row;
                FireTriggers(insert.TableName, TriggerEvent.Insert, TriggerTime.After, null, ref afterRow);
            }
        }
        else if (insert.SelectSource != null)
        {
            rowsAffected = ExecuteInsertFromSelect(insert, table, returningRows);
        }

        m_context.LastInsertRowId = lastRowId;
        m_context.LastChangesCount = rowsAffected;

        if (returningRows != null)
        {
            var schema = BuildReturningSchema(insert.ReturningClause!, table);
            return new WitSqlResult(rowsAffected, returningRows, schema);
        }

        return new WitSqlResult(rowsAffected);
    }

    private int ExecuteInsertFromSelect(WitSqlStatementInsert insert, DefinitionTable table, List<WitSqlRow>? returningRows)
    {
        var iterator = m_planner.Plan(insert.SelectSource!);
        iterator.Open();

        int rowsAffected = 0;
        var evaluator = new ExpressionEvaluator(m_context);
        var dummyRow = new WitSqlRow([], []);
        
        // For INSERT ... SELECT, auto-increment columns are always auto-generated
        var autoGeneratedPkColumns = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var col in table.Columns)
        {
            if (col.IsAutoIncrement && (insert.ColumnNames == null || 
                !insert.ColumnNames.Any(cn => cn.Equals(col.Name, StringComparison.OrdinalIgnoreCase))))
            {
                autoGeneratedPkColumns.Add(col.Name);
            }
        }

        try
        {
            while (iterator.MoveNext())
            {
                var values = new WitSqlValue[table.Columns.Count];
                var columnNames = table.Columns.Select(c => c.Name).ToArray();
                long rowId = 0;

                // Initialize with defaults and auto-increment (skip computed columns)
                for (int i = 0; i < table.Columns.Count; i++)
                {
                    var col = table.Columns[i];
                    if (col.IsComputed)
                    {
                        values[i] = WitSqlValue.Null;
                    }
                    else if (col.Type == WitDataType.RowVersion)
                    {
                        values[i] = WitSqlValue.FromRowVersion(m_context.Database.GetNextRowVersion(table.Name));
                    }
                    else if (col.IsAutoIncrement)
                    {
                        rowId = m_context.Database.GetNextAutoIncrement(table.Name);
                        values[i] = WitSqlValue.FromInt(rowId);
                    }
                    else if (col.DefaultValue != null)
                    {
                        var defaultExpr = Parser.WitSql.ParseExpression(col.DefaultValue);
                        values[i] = evaluator.Evaluate(defaultExpr, dummyRow);
                    }
                    else
                    {
                        values[i] = WitSqlValue.Null;
                    }
                }

                // Map SELECT columns to INSERT columns
                if (insert.ColumnNames != null && insert.ColumnNames.Count > 0)
                {
                    for (int i = 0; i < insert.ColumnNames.Count && i < iterator.Current.ColumnCount; i++)
                    {
                        var colIndex = table.GetOrdinal(insert.ColumnNames[i]);
                        if (colIndex >= 0)
                        {
                            var col = table.Columns[colIndex];
                            if (col.IsComputed)
                            {
                                throw new InvalidOperationException(
                                    $"Cannot INSERT into computed column '{col.Name}'");
                            }
                            if (col.Type == WitDataType.RowVersion)
                            {
                                throw new InvalidOperationException(
                                    $"Cannot INSERT into ROWVERSION column '{col.Name}'");
                            }
                            values[colIndex] = iterator.Current[i];
                        }
                    }
                }
                else
                {
                    int valueIndex = 0;
                    for (int i = 0; i < table.Columns.Count && valueIndex < iterator.Current.ColumnCount; i++)
                    {
                        var col = table.Columns[i];
                        if (!col.IsComputed && col.Type != WitDataType.RowVersion)
                        {
                            values[i] = iterator.Current[valueIndex];
                            valueIndex++;
                        }
                    }
                }

                // Calculate STORED computed columns
                var intermediateRow = new WitSqlRow(values, columnNames);
                for (int i = 0; i < table.Columns.Count; i++)
                {
                    var col = table.Columns[i];
                    if (col.IsComputed && col.IsStored && !string.IsNullOrEmpty(col.ComputedExpression))
                    {
                        var expr = Parser.WitSql.ParseExpression(col.ComputedExpression);
                        values[i] = evaluator.Evaluate(expr, intermediateRow);
                    }
                }

                var row = new WitSqlRow(values, columnNames);

                // Fire BEFORE INSERT triggers
                WitSqlRow? newRow = row;
                if (!FireTriggers(insert.TableName, TriggerEvent.Insert, TriggerTime.Before, null, ref newRow))
                    continue;

                row = newRow!.Value;

                // Check for INSTEAD OF triggers
                WitSqlRow? insteadOfRow = row;
                if (FireInsteadOfTrigger(insert.TableName, TriggerEvent.Insert, null, ref insteadOfRow))
                {
                    rowsAffected++;
                    continue;
                }

                ValidateConstraintsWithAutoGen(table, row, insert.TableName, autoGeneratedPkColumns);
                m_context.Database.InsertRow(insert.TableName, row);
                rowsAffected++;

                // Collect RETURNING row
                if (returningRows != null && insert.ReturningClause != null)
                {
                    var returningRow = BuildReturningRow(row, insert.ReturningClause, table);
                    returningRows.Add(returningRow);
                }

                // Fire AFTER INSERT triggers
                WitSqlRow? afterRow = row;
                FireTriggers(insert.TableName, TriggerEvent.Insert, TriggerTime.After, null, ref afterRow);
            }
        }
        finally
        {
            iterator.Dispose();
        }

        return rowsAffected;
    }

    /// <summary>
    /// Builds an INSERT row and tracks which auto-increment columns were auto-generated.
    /// </summary>
    private (WitSqlRow Row, long RowId, HashSet<string> AutoGeneratedPkColumns) BuildInsertRowWithAutoGenInfo(
        DefinitionTable table,
        IReadOnlyList<string>? columnNames,
        IReadOnlyList<WitSqlExpression> valueExprs,
        HashSet<string>? explicitlySetColumns)
    {
        var evaluator = new ExpressionEvaluator(m_context);
        var dummyRow = new WitSqlRow([], []);

        var values = new WitSqlValue[table.Columns.Count];
        var names = table.Columns.Select(c => c.Name).ToArray();
        long rowId = 0;
        
        // Track which auto-increment columns got auto-generated values
        var autoGeneratedPkColumns = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        // Initialize with defaults (skip computed columns for now)
        for (int i = 0; i < table.Columns.Count; i++)
        {
            var col = table.Columns[i];
            if (col.IsComputed)
            {
                values[i] = WitSqlValue.Null;
            }
            else if (col.Type == WitDataType.RowVersion)
            {
                values[i] = WitSqlValue.FromRowVersion(m_context.Database.GetNextRowVersion(table.Name));
            }
            else if (col.IsAutoIncrement)
            {
                // Check if this column was explicitly specified
                bool isExplicitlySet = explicitlySetColumns?.Contains(col.Name) ?? false;
                
                if (!isExplicitlySet)
                {
                    // Auto-generate the value - mark as auto-generated for skipping UNIQUE check
                    rowId = m_context.Database.GetNextAutoIncrement(table.Name);
                    values[i] = WitSqlValue.FromInt(rowId);
                    autoGeneratedPkColumns.Add(col.Name);
                }
                else
                {
                    // Will be set from explicit value below - need to validate UNIQUE
                    values[i] = WitSqlValue.Null; // Placeholder, will be overwritten
                }
            }
            else if (col.DefaultValue != null)
            {
                var defaultExpr = Parser.WitSql.ParseExpression(col.DefaultValue);
                values[i] = evaluator.Evaluate(defaultExpr, dummyRow);
            }
            else
            {
                values[i] = WitSqlValue.Null;
            }
        }

        // Set specified values
        if (columnNames != null && columnNames.Count > 0)
        {
            for (int i = 0; i < columnNames.Count && i < valueExprs.Count; i++)
            {
                var colIndex = table.GetOrdinal(columnNames[i]);
                if (colIndex >= 0)
                {
                    var col = table.Columns[colIndex];
                    if (col.IsComputed)
                    {
                        throw new InvalidOperationException(
                            $"Cannot INSERT into computed column '{col.Name}'");
                    }
                    if (col.Type == WitDataType.RowVersion)
                    {
                        throw new InvalidOperationException(
                            $"Cannot INSERT into ROWVERSION column '{col.Name}'");
                    }
                    
                    var value = evaluator.Evaluate(valueExprs[i], dummyRow);
                    values[colIndex] = value;
                    
                    // If auto-increment column was explicitly set, get rowId from value
                    // AND update the auto-increment counter if needed
                    if (col.IsAutoIncrement && !value.IsNull)
                    {
                        rowId = value.AsInt64();
                        // Ensure auto-increment counter is at least rowId+1 for next insert
                        m_context.Database.EnsureAutoIncrementAtLeast(table.Name, rowId);
                    }
                }
            }
        }
        else
        {
            // Positional: INSERT INTO table VALUES (val1, val2, ...)
            int valueIndex = 0;
            for (int i = 0; i < table.Columns.Count && valueIndex < valueExprs.Count; i++)
            {
                var col = table.Columns[i];
                if (!col.IsComputed && col.Type != WitDataType.RowVersion)
                {
                    var value = evaluator.Evaluate(valueExprs[valueIndex], dummyRow);
                    values[i] = value;
                    
                    // For positional, auto-increment is considered explicit if provided
                    if (col.IsAutoIncrement)
                    {
                        autoGeneratedPkColumns.Remove(col.Name);
                        if (!value.IsNull)
                        {
                            rowId = value.AsInt64();
                            // Ensure auto-increment counter is at least rowId for next insert
                            m_context.Database.EnsureAutoIncrementAtLeast(table.Name, rowId);
                        }
                    }
                    
                    valueIndex++;
                }
            }
        }

        // Now calculate STORED computed columns
        var intermediateRow = new WitSqlRow(values, names);
        for (int i = 0; i < table.Columns.Count; i++)
        {
            var col = table.Columns[i];
            if (col.IsComputed && col.IsStored && !string.IsNullOrEmpty(col.ComputedExpression))
            {
                var expr = Parser.WitSql.ParseExpression(col.ComputedExpression);
                values[i] = evaluator.Evaluate(expr, intermediateRow);
            }
        }

        // Validate NOT NULL constraints
        for (int i = 0; i < table.Columns.Count; i++)
        {
            var col = table.Columns[i];
            if (!col.Nullable && values[i].IsNull)
            {
                throw new InvalidOperationException($"NOT NULL constraint failed: {table.Name}.{col.Name}");
            }
        }

        return (new WitSqlRow(values, names), rowId, autoGeneratedPkColumns);
    }

    // Keep old method for backward compatibility
    private (WitSqlRow Row, long RowId) BuildInsertRow(
        DefinitionTable table,
        IReadOnlyList<string>? columnNames,
        IReadOnlyList<WitSqlExpression> valueExprs)
    {
        var (row, rowId, _) = BuildInsertRowWithAutoGenInfo(table, columnNames, valueExprs, null);
        return (row, rowId);
    }

    #endregion

    #region Conflict Resolution (UPSERT)

    /// <summary>
    /// Result of conflict resolution check.
    /// </summary>
    private enum ConflictResult
    {
        /// <summary>No conflict, proceed with insert.</summary>
        NoConflict,

        /// <summary>Conflict detected, skip this row.</summary>
        Skip,

        /// <summary>Conflict detected, row was updated.</summary>
        Updated
    }

    /// <summary>
    /// Handles INSERT OR REPLACE, INSERT OR IGNORE, and ON CONFLICT clauses.
    /// </summary>
    private ConflictResult HandleConflictResolution(WitSqlStatementInsert insert, DefinitionTable table, ref WitSqlRow row, ref long rowId)
    {
        // Find conflicting row based on primary key or unique constraints
        var (existingRowId, existingRow) = FindConflictingRow(table, row, insert.OnConflict?.ConflictColumns);

        if (existingRowId == null)
            return ConflictResult.NoConflict;

        // Handle INSERT OR REPLACE
        if (insert.ConflictResolution == ConflictResolutionType.Replace)
        {
            // Delete existing row and proceed with insert
            m_context.Database.DeleteRow(table.Name, existingRowId.Value);
            return ConflictResult.NoConflict;
        }

        // Handle INSERT OR IGNORE
        if (insert.ConflictResolution == ConflictResolutionType.Ignore)
        {
            return ConflictResult.Skip;
        }

        // Handle ON CONFLICT clause
        if (insert.OnConflict != null)
        {
            if (insert.OnConflict.ActionType == ConflictActionType.Nothing)
            {
                return ConflictResult.Skip;
            }

            if (insert.OnConflict.ActionType == ConflictActionType.Update)
            {
                // Set EXCLUDED pseudo-table before evaluating WHERE clause
                // (it may reference EXCLUDED.column)
                m_context.ExcludedRow = row;

                try
                {
                    // Check WHERE clause if present
                    if (insert.OnConflict.WhereClause != null)
                    {
                        var evaluator = new ExpressionEvaluator(m_context);
                        var whereResult = evaluator.Evaluate(insert.OnConflict.WhereClause, existingRow!.Value);
                        if (!whereResult.IsTrue)
                        {
                            return ConflictResult.Skip;
                        }
                    }

                    // Execute UPDATE with SET clauses
                    row = ExecuteUpsertUpdate(table, existingRowId.Value, existingRow!.Value, row, insert.OnConflict.UpdateClauses!);
                    rowId = existingRowId.Value;
                    return ConflictResult.Updated;
                }
                finally
                {
                    m_context.ExcludedRow = null;
                }
            }
        }

        return ConflictResult.NoConflict;
    }

    /// <summary>
    /// Finds a row that conflicts with the given row based on primary key or unique constraints.
    /// Also checks unique indexes for conflict detection.
    /// </summary>
    private (long? RowId, WitSqlRow? Row) FindConflictingRow(DefinitionTable table, WitSqlRow newRow, IReadOnlyList<string>? conflictColumns)
    {
        // If specific conflict columns are specified (ON CONFLICT (columns)), use only those
        if (conflictColumns != null && conflictColumns.Count > 0)
        {
            return FindConflictingRowByColumns(table, newRow, conflictColumns);
        }

        // Check primary key columns first
        if (table.PrimaryKey != null && table.PrimaryKey.Count > 0)
        {
            // Only check if all PK columns have non-null values in newRow
            bool allPkColumnsHaveValues = table.PrimaryKey.All(pkCol =>
            {
                if (!newRow.TryGetValue(pkCol, out var value))
                    return false;
                return !value.IsNull;
            });

            if (allPkColumnsHaveValues)
            {
                var result = FindConflictingRowByColumns(table, newRow, table.PrimaryKey);
                if (result.RowId != null)
                    return result;
            }
        }

        // Check unique columns on the table
        var uniqueColumns = table.Columns.Where(c => c.IsUnique).Select(c => c.Name).ToList();
        foreach (var uniqueCol in uniqueColumns)
        {
            if (newRow.TryGetValue(uniqueCol, out var value) && !value.IsNull)
            {
                var result = FindConflictingRowByColumns(table, newRow, [uniqueCol]);
                if (result.RowId != null)
                    return result;
            }
        }

        // Check unique indexes
        var uniqueIndexes = m_context.Database.GetTableIndexes(table.Name).Where(i => i.IsUnique && !i.IsPrimaryKey);
        foreach (var index in uniqueIndexes)
        {
            // Only check if all index columns have non-null values in newRow
            bool allIndexColumnsHaveValues = index.Columns.All(col =>
            {
                if (!newRow.TryGetValue(col, out var value))
                    return false;
                return !value.IsNull;
            });

            if (allIndexColumnsHaveValues)
            {
                var result = FindConflictingRowByColumns(table, newRow, index.Columns);
                if (result.RowId != null)
                    return result;
            }
        }

        return (null, null);
    }

    /// <summary>
    /// Finds a row that conflicts by checking specific columns.
    /// </summary>
    private (long? RowId, WitSqlRow? Row) FindConflictingRowByColumns(DefinitionTable table, WitSqlRow newRow, IReadOnlyList<string> columnsToCheck)
    {
        if (columnsToCheck.Count == 0)
            return (null, null);

        var iterator = m_context.Database.CreateTableScan(table.Name);
        iterator.Open();

        try
        {
            while (iterator.MoveNext())
            {
                var existingRow = iterator.Current;
                bool allMatch = true;

                foreach (var colName in columnsToCheck)
                {
                    if (!newRow.TryGetValue(colName, out var newValue))
                    {
                        allMatch = false;
                        break;
                    }

                    if (!existingRow.TryGetValue(colName, out var existingValue))
                    {
                        allMatch = false;
                        break;
                    }

                    // Skip NULL values - NULL does not equal NULL for conflict detection
                    if (newValue.IsNull || existingValue.IsNull)
                    {
                        allMatch = false;
                        break;
                    }

                    if (!newValue.Equals(existingValue))
                    {
                        allMatch = false;
                        break;
                    }
                }

                if (allMatch)
                {
                    var rowId = existingRow["_rowid"].AsInt64();
                    return (rowId, existingRow);
                }
            }
        }
        finally
        {
            iterator.Dispose();
        }

        return (null, null);
    }

    /// <summary>
    /// Executes the UPDATE part of an upsert operation.
    /// Note: ExcludedRow must be set in context before calling this method.
    /// </summary>
    private WitSqlRow ExecuteUpsertUpdate(DefinitionTable table, long rowId, WitSqlRow existingRow, WitSqlRow newRow, IReadOnlyList<ClauseSet> updateClauses)
    {
        var evaluator = new ExpressionEvaluator(m_context);
        var newValues = existingRow.Values.ToArray();
        var columnNames = existingRow.ColumnNames.ToArray();

        // EXCLUDED pseudo-table is already set in context by HandleConflictResolution
        foreach (var setClause in updateClauses)
        {
            for (int i = 0; i < columnNames.Length; i++)
            {
                if (columnNames[i].Equals(setClause.ColumnName, StringComparison.OrdinalIgnoreCase))
                {
                    newValues[i] = evaluator.Evaluate(setClause.Value, existingRow);
                    break;
                }
            }
        }

        // Recalculate STORED computed columns
        var storedComputedColumns = table.Columns.Where(c => c.IsComputed && c.IsStored).ToList();
        var intermediateRow = new WitSqlRow(newValues, columnNames);

        foreach (var computedCol in storedComputedColumns)
        {
            for (int i = 0; i < columnNames.Length; i++)
            {
                if (columnNames[i].Equals(computedCol.Name, StringComparison.OrdinalIgnoreCase))
                {
                    if (!string.IsNullOrEmpty(computedCol.ComputedExpression))
                    {
                        var expr = Parser.WitSql.ParseExpression(computedCol.ComputedExpression);
                        newValues[i] = evaluator.Evaluate(expr, intermediateRow);
                    }
                    break;
                }
            }
        }

        var updatedRow = new WitSqlRow(newValues, columnNames);

        // Validate constraints
        ValidateNotNullConstraints(table, updatedRow);
        ValidateConstraints(table, updatedRow, table.Name, rowId);

        // Perform update
        m_context.Database.UpdateRow(table.Name, rowId, updatedRow);

        return updatedRow;
    }

    #endregion
}
