using OutWit.Database.Definitions;
using OutWit.Database.Expressions;
using OutWit.Database.Parser;
using OutWit.Database.Sql;
using OutWit.Database.Values;

namespace OutWit.Database.Statements;

public sealed partial class StatementExecutor
{
    #region Constraint Validation

    /// <summary>
    /// Validates all constraints for a row.
    /// </summary>
    private void ValidateConstraints(DefinitionTable table, WitSqlRow row, string tableName, long? excludeRowId = null)
    {
        ValidateUniqueConstraints(table, row, tableName, excludeRowId);
        ValidateCheckConstraints(table, row, tableName);
        ValidateForeignKeyConstraints(table, row, tableName);
        ValidateNamedConstraints(table, row, tableName, excludeRowId);
    }

    /// <summary>
    /// Validates all constraints for a row, with ability to skip UNIQUE validation for auto-generated columns.
    /// </summary>
    /// <param name="table">The table definition.</param>
    /// <param name="row">The row to validate.</param>
    /// <param name="tableName">The table name.</param>
    /// <param name="autoGeneratedPkColumns">Set of column names that have auto-generated values (skip UNIQUE check for these).</param>
    /// <param name="excludeRowId">Row ID to exclude from UNIQUE check (for UPDATE).</param>
    private void ValidateConstraintsWithAutoGen(
        DefinitionTable table, 
        WitSqlRow row, 
        string tableName, 
        HashSet<string>? autoGeneratedPkColumns,
        long? excludeRowId = null)
    {
        ValidateUniqueConstraintsWithAutoGen(table, row, tableName, autoGeneratedPkColumns, excludeRowId);
        ValidateCheckConstraints(table, row, tableName);
        ValidateForeignKeyConstraints(table, row, tableName);
        ValidateNamedConstraints(table, row, tableName, excludeRowId);
    }

    #endregion

    #region Cascading Actions (ON DELETE/UPDATE CASCADE, SET NULL, etc.)

    /// <summary>
    /// Handles cascading actions when a row is deleted or its primary key is updated.
    /// This method finds all foreign keys that reference this table and applies the appropriate action.
    /// </summary>
    /// <param name="tableName">The table from which the row is being deleted/updated.</param>
    /// <param name="row">The row being deleted/updated.</param>
    /// <param name="isDelete">True if this is a DELETE operation, false for UPDATE.</param>
    private void HandleCascadingActions(string tableName, WitSqlRow row, bool isDelete)
    {
        var parentTable = m_context.Database.GetTable(tableName);
        if (parentTable == null)
            return;

        // Get the primary key columns of the parent table
        var pkColumns = parentTable.PrimaryKey?.ToList();
        if (pkColumns == null || pkColumns.Count == 0)
        {
            // Check for single-column PK via column flags
            var pkCol = parentTable.Columns.FirstOrDefault(c => c.IsPrimaryKey);
            if (pkCol != null)
            {
                pkColumns = [pkCol.Name];
            }
            else
            {
                return; // No primary key, nothing to cascade
            }
        }

        // Get the PK values from the row being deleted
        var pkValues = pkColumns.Select(col => row[col]).ToArray();
        
        // If all PK values are null, nothing to cascade
        if (pkValues.All(v => v.IsNull))
            return;

        // Find all tables that have foreign keys referencing this table
        foreach (var childTableName in GetAllTableNames())
        {
            if (childTableName.Equals(tableName, StringComparison.OrdinalIgnoreCase))
                continue; // Skip self-reference for now

            var childTable = m_context.Database.GetTable(childTableName);
            if (childTable == null)
                continue;

            // Check column-level FK constraints
            foreach (var col in childTable.Columns)
            {
                if (col.ForeignKey != null && 
                    col.ForeignKey.ForeignTable.Equals(tableName, StringComparison.OrdinalIgnoreCase))
                {
                    ApplyCascadingAction(childTableName, childTable, col.ForeignKey, pkColumns, pkValues, isDelete);
                }
            }

            // Check table-level FK constraints
            if (childTable.ForeignKeys != null)
            {
                foreach (var fk in childTable.ForeignKeys)
                {
                    if (fk.ForeignTable.Equals(tableName, StringComparison.OrdinalIgnoreCase))
                    {
                        ApplyCascadingAction(childTableName, childTable, fk, pkColumns, pkValues, isDelete);
                    }
                }
            }

            // Check named constraints
            if (childTable.NamedConstraints != null)
            {
                foreach (var constraint in childTable.NamedConstraints)
                {
                    if (constraint.Type == ConstraintType.ForeignKey && 
                        constraint.ForeignKey != null &&
                        constraint.ForeignKey.ForeignTable.Equals(tableName, StringComparison.OrdinalIgnoreCase))
                    {
                        ApplyCascadingAction(childTableName, childTable, constraint.ForeignKey, pkColumns, pkValues, isDelete);
                    }
                }
            }
        }
    }

    /// <summary>
    /// Gets all table names in the database.
    /// </summary>
    private IEnumerable<string> GetAllTableNames()
    {
        // We need to get all tables from the database
        // Use INFORMATION_SCHEMA or iterate through known tables
        if (m_context.Database is Engine.WitSqlEngine engine)
        {
            return engine.GetAllTableNames();
        }
        
        return [];
    }

    /// <summary>
    /// Applies the cascading action for a specific foreign key constraint.
    /// </summary>
    private void ApplyCascadingAction(
        string childTableName,
        DefinitionTable childTable,
        DefinitionForeignKey fk,
        List<string> parentPkColumns,
        WitSqlValue[] parentPkValues,
        bool isDelete)
    {
        // Determine which action to apply
        var action = isDelete ? fk.OnDelete : fk.OnUpdate;

        // NoAction and Restrict don't cascade - they just prevent the operation
        // For NoAction/Restrict, we should check if there are referencing rows and throw an error
        if (action == ReferenceAction.NoAction || action == ReferenceAction.Restrict)
        {
            // Check if there are any child rows referencing this parent
            if (HasReferencingRows(childTableName, fk, parentPkColumns, parentPkValues))
            {
                throw new InvalidOperationException(
                    $"Cannot delete row from '{parentPkColumns[0]}': foreign key constraint '{childTableName}' references it");
            }
            return;
        }

        // Find all child rows that reference the parent row
        var childRowsToProcess = FindReferencingRows(childTableName, fk, parentPkColumns, parentPkValues);
        
        if (childRowsToProcess.Count == 0)
            return;

        switch (action)
        {
            case ReferenceAction.Cascade:
                // Delete all referencing child rows
                foreach (var (rowId, _) in childRowsToProcess)
                {
                    // Recursively handle cascades for this child row
                    var childRow = GetRowById(childTableName, rowId);
                    if (childRow.HasValue)
                    {
                        HandleCascadingActions(childTableName, childRow.Value, isDelete: true);
                    }
                    
                    m_context.Database.DeleteRow(childTableName, rowId);
                }
                break;

            case ReferenceAction.SetNull:
                // Set the FK columns to NULL
                foreach (var (rowId, oldRow) in childRowsToProcess)
                {
                    var newRow = SetColumnsToNull(oldRow, fk.Columns, childTable);
                    m_context.Database.UpdateRow(childTableName, rowId, newRow);
                }
                break;

            case ReferenceAction.SetDefault:
                // Set the FK columns to their default values
                foreach (var (rowId, oldRow) in childRowsToProcess)
                {
                    var newRow = SetColumnsToDefault(oldRow, fk.Columns, childTable);
                    m_context.Database.UpdateRow(childTableName, rowId, newRow);
                }
                break;
        }
    }

    /// <summary>
    /// Checks if there are any rows in the child table that reference the parent row.
    /// </summary>
    private bool HasReferencingRows(
        string childTableName,
        DefinitionForeignKey fk,
        List<string> parentPkColumns,
        WitSqlValue[] parentPkValues)
    {
        var foreignColumns = fk.ForeignColumns?.ToList() ?? parentPkColumns;
        
        var iterator = m_context.Database.CreateTableScan(childTableName);
        iterator.Open();
        
        try
        {
            while (iterator.MoveNext())
            {
                if (RowReferencesParent(iterator.Current, fk.Columns, foreignColumns, parentPkValues))
                    return true;
            }
        }
        finally
        {
            iterator.Dispose();
        }
        
        return false;
    }

    /// <summary>
    /// Finds all rows in the child table that reference the parent row.
    /// </summary>
    private List<(long RowId, WitSqlRow Row)> FindReferencingRows(
        string childTableName,
        DefinitionForeignKey fk,
        List<string> parentPkColumns,
        WitSqlValue[] parentPkValues)
    {
        var result = new List<(long RowId, WitSqlRow Row)>();
        var foreignColumns = fk.ForeignColumns?.ToList() ?? parentPkColumns;
        
        var iterator = m_context.Database.CreateTableScan(childTableName);
        iterator.Open();
        
        try
        {
            while (iterator.MoveNext())
            {
                if (RowReferencesParent(iterator.Current, fk.Columns, foreignColumns, parentPkValues))
                {
                    var rowId = iterator.Current["_rowid"].AsInt64();
                    result.Add((rowId, iterator.Current));
                }
            }
        }
        finally
        {
            iterator.Dispose();
        }
        
        return result;
    }

    /// <summary>
    /// Checks if a child row references the parent row through the foreign key.
    /// </summary>
    private static bool RowReferencesParent(
        WitSqlRow childRow,
        IReadOnlyList<string> fkColumns,
        List<string> parentPkColumns,
        WitSqlValue[] parentPkValues)
    {
        for (int i = 0; i < fkColumns.Count && i < parentPkValues.Length; i++)
        {
            var childValue = childRow[fkColumns[i]];
            var parentValue = parentPkValues[i];
            
            // NULL values don't match
            if (childValue.IsNull || parentValue.IsNull)
                return false;
            
            if (!childValue.Equals(parentValue))
                return false;
        }
        
        return true;
    }

    /// <summary>
    /// Gets a row by its row ID.
    /// </summary>
    private WitSqlRow? GetRowById(string tableName, long rowId)
    {
        var iterator = m_context.Database.CreateTableScan(tableName);
        iterator.Open();
        
        try
        {
            while (iterator.MoveNext())
            {
                if (iterator.Current["_rowid"].AsInt64() == rowId)
                    return iterator.Current;
            }
        }
        finally
        {
            iterator.Dispose();
        }
        
        return null;
    }

    /// <summary>
    /// Creates a new row with specified columns set to NULL.
    /// </summary>
    private static WitSqlRow SetColumnsToNull(WitSqlRow oldRow, IReadOnlyList<string> columnsToNull, DefinitionTable table)
    {
        var newValues = new WitSqlValue[oldRow.ColumnCount];
        var newColumns = new string[oldRow.ColumnCount];
        
        for (int i = 0; i < oldRow.ColumnCount; i++)
        {
            var colName = oldRow.GetColumnName(i);
            newColumns[i] = colName;
            
            if (columnsToNull.Any(c => c.Equals(colName, StringComparison.OrdinalIgnoreCase)))
            {
                newValues[i] = WitSqlValue.Null;
            }
            else
            {
                newValues[i] = oldRow[i];
            }
        }
        
        return new WitSqlRow(newValues, newColumns);
    }

    /// <summary>
    /// Creates a new row with specified columns set to their default values.
    /// </summary>
    private WitSqlRow SetColumnsToDefault(WitSqlRow oldRow, IReadOnlyList<string> columnsToDefault, DefinitionTable table)
    {
        var newValues = new WitSqlValue[oldRow.ColumnCount];
        var newColumns = new string[oldRow.ColumnCount];
        var evaluator = new ExpressionEvaluator(m_context);
        
        for (int i = 0; i < oldRow.ColumnCount; i++)
        {
            var colName = oldRow.GetColumnName(i);
            newColumns[i] = colName;
            
            if (columnsToDefault.Any(c => c.Equals(colName, StringComparison.OrdinalIgnoreCase)))
            {
                // Get the default value for this column
                var col = table.GetColumn(colName);
                if (col?.DefaultValue != null)
                {
                    var defaultExpr = WitSql.ParseExpression(col.DefaultValue);
                    var defaultValue = evaluator.Evaluate(defaultExpr, oldRow);
                    newValues[i] = defaultValue;
                }
                else
                {
                    newValues[i] = WitSqlValue.Null;
                }
            }
            else
            {
                newValues[i] = oldRow[i];
            }
        }
        
        return new WitSqlRow(newValues, newColumns);
    }

    #endregion

    #region UNIQUE Constraints

    private void ValidateUniqueConstraints(DefinitionTable table, WitSqlRow row, string tableName, long? excludeRowId = null)
    {
        ValidateUniqueConstraintsWithAutoGen(table, row, tableName, null, excludeRowId);
    }

    /// <summary>
    /// Validates UNIQUE constraints, with ability to skip validation for auto-generated columns.
    /// </summary>
    private void ValidateUniqueConstraintsWithAutoGen(
        DefinitionTable table, 
        WitSqlRow row, 
        string tableName, 
        HashSet<string>? autoGeneratedPkColumns,
        long? excludeRowId = null)
    {
        var constraintSets = new List<(IReadOnlyList<string> Columns, string Description, bool CanSkip)>();

        // 1. Add column-level UNIQUE constraints (single columns)
        foreach (var col in table.Columns)
        {
            if (col.IsUnique)
            {
                bool canSkip = autoGeneratedPkColumns?.Contains(col.Name) ?? false;
                constraintSets.Add(([col.Name], $"UNIQUE constraint on {tableName}.{col.Name}", canSkip));
            }
        }

        // 2. Add PRIMARY KEY as unique constraint
        if (table.PrimaryKey != null && table.PrimaryKey.Count > 0)
        {
            bool canSkip = autoGeneratedPkColumns != null && 
                           table.PrimaryKey.All(pk => autoGeneratedPkColumns.Contains(pk));
            constraintSets.Add((table.PrimaryKey, $"PRIMARY KEY constraint on {tableName}", canSkip));
        }
        else
        {
            // Single-column PRIMARY KEY via column flags
            foreach (var col in table.Columns)
            {
                if (col.IsPrimaryKey)
                {
                    bool alreadyAdded = constraintSets.Any(cs =>
                        cs.Columns.Count == 1 &&
                        cs.Columns[0].Equals(col.Name, StringComparison.OrdinalIgnoreCase));

                    if (!alreadyAdded)
                    {
                        bool canSkip = autoGeneratedPkColumns?.Contains(col.Name) ?? false;
                        constraintSets.Add(([col.Name], $"PRIMARY KEY constraint on {tableName}.{col.Name}", canSkip));
                    }
                }
            }
        }

        // 3. Add table-level composite UNIQUE constraints
        if (table.UniqueConstraints != null)
        {
            foreach (var uniqueColumns in table.UniqueConstraints)
            {
                bool canSkip = autoGeneratedPkColumns != null && 
                               uniqueColumns.All(c => autoGeneratedPkColumns.Contains(c));
                constraintSets.Add((uniqueColumns, $"UNIQUE constraint on {tableName}({string.Join(", ", uniqueColumns)})", canSkip));
            }
        }

        if (constraintSets.Count == 0)
            return;

        // Filter out constraints that can be skipped (auto-generated values are guaranteed unique)
        // Also filter out constraints where all values are NULL
        var activeConstraints = constraintSets
            .Where(cs => !cs.CanSkip)
            .Where(cs => !cs.Columns.All(c => row[c].IsNull))
            .Select(cs => (cs.Columns, cs.Description))
            .ToList();
            
        if (activeConstraints.Count == 0)
            return;

        // Get indexes once - avoid repeated calls
        IEnumerable<DefinitionIndex>? indexes = null;
        var remainingConstraints = new List<(IReadOnlyList<string> Columns, string Description)>();
        
        foreach (var (columns, description) in activeConstraints)
        {
            var keyValues = columns.Select(c => row[c]).ToArray();
            
            // Skip if any value is NULL - NULLs don't violate UNIQUE
            if (keyValues.Any(v => v.IsNull))
                continue;
                
            bool foundViaIndex = false;
            
            // Lazy load indexes only when needed
            indexes ??= m_context.Database.GetTableIndexes(tableName).ToList();
            
            // Check if there's a unique index on these exact columns
            foreach (var index in indexes)
            {
                if (index.IsUnique && 
                    index.Columns.Count == columns.Count &&
                    index.Columns.All(ic => columns.Any(c => c.Equals(ic, StringComparison.OrdinalIgnoreCase))))
                {
                    try
                    {
                        using var seekIterator = m_context.Database.CreateIndexSeek(tableName, index.Name, keyValues);
                        seekIterator.Open();
                        
                        while (seekIterator.MoveNext())
                        {
                            var existingRowId = seekIterator.Current["_rowid"].AsInt64();
                            
                            // Skip the row being updated
                            if (excludeRowId.HasValue && existingRowId == excludeRowId.Value)
                                continue;
                            
                            // Found duplicate!
                            throw new InvalidOperationException(
                                $"UNIQUE constraint failed: {tableName}.{columns[0]} (duplicate value: {row[columns[0]].AsString()})");
                        }
                        
                        foundViaIndex = true;
                    }
                    catch (InvalidOperationException)
                    {
                        // Re-throw UNIQUE constraint violations
                        throw;
                    }
                    catch
                    {
                        // Index seek failed - fall back to scan
                        foundViaIndex = false;
                    }
                    
                    break;
                }
            }
            
            if (!foundViaIndex)
            {
                remainingConstraints.Add((columns, description));
            }
        }

        // Fall back to full scan for constraints without indexes
        if (remainingConstraints.Count == 0)
            return;

        var iterator = m_context.Database.CreateTableScan(tableName);
        iterator.Open();

        try
        {
            while (iterator.MoveNext())
            {
                var existingRow = iterator.Current;

                // Skip the row being updated (for UPDATE operations)
                if (excludeRowId.HasValue)
                {
                    var rowIdValue = existingRow["_rowid"];
                    if (!rowIdValue.IsNull && rowIdValue.AsInt64() == excludeRowId.Value)
                        continue;
                }

                // Check each remaining constraint set
                foreach (var (columns, description) in remainingConstraints)
                {
                    if (IsUniqueViolation(row, existingRow, columns))
                    {
                        throw new InvalidOperationException(
                            $"UNIQUE constraint failed: {tableName}.{columns[0]} (duplicate value: {row[columns[0]].AsString()})");
                    }
                }
            }
        }
        finally
        {
            iterator.Dispose();
        }
    }
    
    private static bool IsUniqueViolation(WitSqlRow newRow, WitSqlRow existingRow, IReadOnlyList<string> columns)
    {
        foreach (var colName in columns)
        {
            var newValue = newRow[colName];
            var existingValue = existingRow[colName];

            // NULL values don't violate UNIQUE constraint
            if (newValue.IsNull || existingValue.IsNull)
                return false;

            if (!newValue.Equals(existingValue))
                return false;
        }

        return true; // All columns match - it's a duplicate
    }

    #endregion

    #region CHECK Constraints

    private void ValidateCheckConstraints(DefinitionTable table, WitSqlRow row, string tableName)
    {
        var evaluator = new ExpressionEvaluator(m_context);

        // Validate column-level CHECK constraints
        foreach (var col in table.Columns)
        {
            if (col.CheckExpression == null)
                continue;

            // Skip CHECK if the column value is NULL (SQL standard behavior)
            var columnValue = row[col.Name];
            if (columnValue.IsNull)
                continue;

            var checkExpr = WitSql.ParseExpression(col.CheckExpression);
            var result = evaluator.Evaluate(checkExpr, row);

            // Skip if result is NULL
            if (result.IsNull)
                continue;

            if (!result.AsBool())
            {
                throw new InvalidOperationException($"CHECK constraint failed for column {tableName}.{col.Name}");
            }
        }

        // Validate table-level CHECK constraints
        if (table.CheckExpressions != null)
        {
            foreach (var checkSql in table.CheckExpressions)
            {
                var checkExpr = WitSql.ParseExpression(checkSql);
                var result = evaluator.Evaluate(checkExpr, row);

                // Skip if result is NULL
                if (result.IsNull)
                    continue;

                if (!result.AsBool())
                {
                    throw new InvalidOperationException($"CHECK constraint failed for table {tableName}");
                }
            }
        }
    }

    #endregion

    #region FOREIGN KEY Constraints

    private void ValidateForeignKeyConstraints(DefinitionTable table, WitSqlRow row, string tableName)
    {
        // Validate column-level FK constraints
        foreach (var col in table.Columns)
        {
            if (col.ForeignKey != null)
            {
                ValidateForeignKeyReference(col.ForeignKey, row, tableName);
            }
        }

        // Validate table-level FK constraints
        if (table.ForeignKeys != null)
        {
            foreach (var fk in table.ForeignKeys)
            {
                ValidateForeignKeyReference(fk, row, tableName);
            }
        }
    }

    private void ValidateForeignKeyReference(DefinitionForeignKey fk, WitSqlRow row, string tableName)
    {
        var foreignTable = m_context.Database.GetTable(fk.ForeignTable)
            ?? throw new InvalidOperationException($"Referenced table '{fk.ForeignTable}' not found");

        // Get local values for FK columns
        var localValues = new List<WitSqlValue>();
        bool allNull = true;

        foreach (var colName in fk.Columns)
        {
            var val = row[colName];
            localValues.Add(val);
            if (!val.IsNull) allNull = false;
        }

        // NULL values don't violate FK constraint
        if (allNull)
            return;

        // Determine foreign columns to check
        var foreignColumns = fk.ForeignColumns?.ToList()
            ?? foreignTable.PrimaryKey?.ToList()
            ?? throw new InvalidOperationException(
                $"Cannot validate FK constraint: referenced table '{fk.ForeignTable}' has no primary key");

        // Scan foreign table to find matching row
        var iterator = m_context.Database.CreateTableScan(fk.ForeignTable);
        iterator.Open();
        bool found = false;

        try
        {
            while (iterator.MoveNext())
            {
                var foreignRow = iterator.Current;
                bool matches = true;

                for (int i = 0; i < localValues.Count && i < foreignColumns.Count; i++)
                {
                    var localVal = localValues[i];
                    var foreignVal = foreignRow[foreignColumns[i]];

                    if (localVal.IsNull || foreignVal.IsNull || !localVal.Equals(foreignVal))
                    {
                        matches = false;
                        break;
                    }
                }

                if (matches)
                {
                    found = true;
                    break;
                }
            }
        }
        finally
        {
            iterator.Dispose();
        }

        if (!found)
        {
            var valuesStr = string.Join(", ", localValues.Select(v => v.AsString()));
            throw new InvalidOperationException(
                $"FOREIGN KEY constraint failed: {tableName} -> {fk.ForeignTable} (values: {valuesStr})");
        }
    }

    #endregion

    #region Named Constraints (via ALTER TABLE ADD CONSTRAINT)

    /// <summary>
    /// Validates named constraints added via ALTER TABLE ADD CONSTRAINT.
    /// </summary>
    private void ValidateNamedConstraints(DefinitionTable table, WitSqlRow row, string tableName, long? excludeRowId = null)
    {
        if (table.NamedConstraints == null || table.NamedConstraints.Count == 0)
            return;

        var evaluator = new ExpressionEvaluator(m_context);

        foreach (var constraint in table.NamedConstraints)
        {
            switch (constraint.Type)
            {
                case ConstraintType.Check:
                    ValidateNamedCheckConstraint(constraint, row, tableName, evaluator);
                    break;

                case ConstraintType.Unique:
                    ValidateNamedUniqueConstraint(constraint, row, tableName, excludeRowId);
                    break;

                case ConstraintType.ForeignKey:
                    ValidateNamedForeignKeyConstraint(constraint, row, tableName);
                    break;

                // PRIMARY KEY constraints are not added via ALTER TABLE
            }
        }
    }

    private static void ValidateNamedCheckConstraint(
        DefinitionNamedConstraint constraint, 
        WitSqlRow row, 
        string tableName,
        ExpressionEvaluator evaluator)
    {
        if (string.IsNullOrEmpty(constraint.CheckExpression))
            return;

        var checkExpr = WitSql.ParseExpression(constraint.CheckExpression);
        var result = evaluator.Evaluate(checkExpr, row);

        // Skip if result is NULL (SQL standard: NULL is not FALSE)
        if (result.IsNull)
            return;

        if (!result.AsBool())
        {
            throw new InvalidOperationException(
                $"CHECK constraint '{constraint.Name}' failed for table {tableName}");
        }
    }

    private void ValidateNamedUniqueConstraint(
        DefinitionNamedConstraint constraint, 
        WitSqlRow row, 
        string tableName,
        long? excludeRowId)
    {
        if (constraint.Columns == null || constraint.Columns.Count == 0)
            return;

        // Check if all values are NULL - NULLs don't violate UNIQUE
        bool allNull = constraint.Columns.All(col => row[col].IsNull);
        if (allNull)
            return;

        // Scan existing rows to check for duplicates
        var iterator = m_context.Database.CreateTableScan(tableName);
        iterator.Open();

        try
        {
            while (iterator.MoveNext())
            {
                var existingRow = iterator.Current;

                // Skip the row being updated
                if (excludeRowId.HasValue)
                {
                    var rowIdValue = existingRow["_rowid"];
                    if (!rowIdValue.IsNull && rowIdValue.AsInt64() == excludeRowId.Value)
                        continue;
                }

                if (IsUniqueViolation(row, existingRow, constraint.Columns))
                {
                    throw new InvalidOperationException(
                        $"UNIQUE constraint '{constraint.Name}' failed for table {tableName}");
                }
            }
        }
        finally
        {
            iterator.Dispose();
        }
    }

    private void ValidateNamedForeignKeyConstraint(
        DefinitionNamedConstraint constraint, 
        WitSqlRow row, 
        string tableName)
    {
        if (constraint.ForeignKey == null)
            return;

        ValidateForeignKeyReference(constraint.ForeignKey, row, tableName);
    }

    #endregion
}
