using OutWit.Database.Definitions;
using OutWit.Database.Expressions;
using OutWit.Database.Parser;
using OutWit.Database.Parser.Statements;
using OutWit.Database.Sql;
using OutWit.Database.Types;
using OutWit.Database.Values;

namespace OutWit.Database.Statements;

public sealed partial class StatementExecutor
{
    #region Fields

    /// <summary>
    /// Rows whose cascade is currently in flight, so a reference cycle stops instead of recursing
    /// until the stack ends. Keyed by table and row id.
    /// </summary>
    private readonly HashSet<(string Table, long RowId)> m_cascadingRows = new();

    #endregion

    #region Constraint Validation

    /// <summary>
    /// Validates all constraints for a row.
    /// </summary>
    private void ValidateConstraints(DefinitionTable table, WitSqlRow row, string tableName, long? excludeRowId = null)
    {
        ValidateDeclaredSizes(table, row, tableName);
        ValidateUniqueConstraints(table, row, tableName, excludeRowId);
        ValidateCheckConstraints(table, row, tableName);
        ValidateForeignKeyConstraints(table, row, tableName);
        ValidateNamedConstraints(table, row, tableName, excludeRowId);
    }

    /// <summary>
    /// Validates all constraints for a row, with ability to skip UNIQUE validation for auto-generated columns.
    /// </summary>
    /// <param name="table">The table definition.</param>
    /// <param name="row">The row to validate.</param>
    /// <param name="tableName">The table name.</param>
    /// <param name="autoGeneratedPkColumns">Set of column names that have auto-generated values (skip UNIQUE check for these).</param>
    /// <param name="excludeRowId">Row ID to exclude from UNIQUE check (for UPDATE).</param>
    private void ValidateConstraintsWithAutoGen(
        DefinitionTable table, 
        WitSqlRow row, 
        string tableName, 
        HashSet<string>? autoGeneratedPkColumns,
        long? excludeRowId = null)
    {
        ValidateDeclaredSizes(table, row, tableName);
        ValidateUniqueConstraintsWithAutoGen(table, row, tableName, autoGeneratedPkColumns, excludeRowId);
        ValidateCheckConstraints(table, row, tableName);
        ValidateForeignKeyConstraints(table, row, tableName);
        ValidateNamedConstraints(table, row, tableName, excludeRowId);
    }

    #endregion

    #region Cascading Actions (ON DELETE/UPDATE CASCADE, SET NULL, etc.)

    /// <summary>
    /// Handles cascading actions when a row is deleted or its primary key is updated.
    /// This method finds all foreign keys that reference this table and applies the appropriate action.
    /// </summary>
    /// <param name="tableName">The table from which the row is being deleted/updated.</param>
    /// <param name="row">The row being deleted/updated.</param>
    /// <param name="isDelete">True if this is a DELETE operation, false for UPDATE.</param>
    private void HandleCascadingActions(string tableName, WitSqlRow row, bool isDelete)
    {
        var parentTable = m_context.Database.GetTable(tableName);
        if (parentTable == null)
            return;

        // Cascading is recursive: a cascaded child is itself cascaded from. Once self-references
        // are allowed, a cycle - A parents B, B parents A, reachable whenever the key is nullable -
        // would recurse until the stack ends, and a StackOverflowException cannot be caught: it
        // takes the host process down. Tracking the rows already in flight bounds it exactly,
        // without an arbitrary depth limit that would silently truncate a deep but legitimate tree.
        var parentRowId = TryGetRowId(row);
        if (parentRowId.HasValue && !m_cascadingRows.Add((tableName, parentRowId.Value)))
            return;

        try
        {
            HandleCascadingActionsCore(tableName, parentTable, row, parentRowId, isDelete);
        }
        finally
        {
            if (parentRowId.HasValue)
                m_cascadingRows.Remove((tableName, parentRowId.Value));
        }
    }

    private static long? TryGetRowId(WitSqlRow row) =>
        row.TryGetValue("_rowid", out var value) && !value.IsNull ? value.AsInt64() : null;

    private void HandleCascadingActionsCore(
        string tableName,
        DefinitionTable parentTable,
        WitSqlRow row,
        long? parentRowId,
        bool isDelete)
    {

        // Get the primary key columns of the parent table
        var pkColumns = parentTable.PrimaryKey?.ToList();
        if (pkColumns == null || pkColumns.Count == 0)
        {
            // Check for single-column PK via column flags
            var pkCol = parentTable.Columns.FirstOrDefault(c => c.IsPrimaryKey);
            if (pkCol != null)
            {
                pkColumns = [pkCol.Name];
            }
            else
            {
                return; // No primary key, nothing to cascade
            }
        }

        // Get the PK values from the row being deleted
        var pkValues = pkColumns.Select(col => row[col]).ToArray();
        
        // If all PK values are null, nothing to cascade
        if (pkValues.All(v => v.IsNull))
            return;

        // Materialize the table list to avoid enumeration issues when modifying database
        var allTableNames = GetAllTableNames().ToList();

        foreach (var (childTableName, childTable, fk) in FindReferencingForeignKeys(tableName, allTableNames))
        {
            // Only a self-reference can turn up the parent row in its own child scan.
            var excludeRowId = childTableName.Equals(tableName, StringComparison.OrdinalIgnoreCase)
                ? parentRowId
                : null;

            CascadeToChild(childTableName, childTable, fk, row, pkColumns, isDelete, excludeRowId);
        }
    }

    /// <summary>
    /// Enumerates every foreign key pointing at <paramref name="tableName"/>, from any of the three
    /// places one can be declared: on a column, on the table, or as a named constraint.
    /// </summary>
    /// <remarks>
    /// Self-references are included. They used to be skipped outright, which made ON DELETE CASCADE
    /// leave the child behind and - the damaging half - made ON DELETE RESTRICT raise nothing, so
    /// the safe-looking declaration was the one that orphaned rows.
    /// </remarks>
    private IEnumerable<(string ChildTableName, DefinitionTable ChildTable, DefinitionForeignKey Fk)>
        FindReferencingForeignKeys(string tableName, List<string> allTableNames)
    {
        foreach (var childTableName in allTableNames)
        {
            var childTable = m_context.Database.GetTable(childTableName);
            if (childTable == null)
                continue;

            foreach (var col in childTable.Columns)
            {
                if (col.ForeignKey != null && PointsAt(col.ForeignKey, tableName))
                    yield return (childTableName, childTable, col.ForeignKey);
            }

            if (childTable.ForeignKeys != null)
            {
                foreach (var fk in childTable.ForeignKeys)
                {
                    if (PointsAt(fk, tableName))
                        yield return (childTableName, childTable, fk);
                }
            }

            if (childTable.NamedConstraints != null)
            {
                foreach (var constraint in childTable.NamedConstraints)
                {
                    if (constraint.Type == ConstraintType.ForeignKey &&
                        constraint.ForeignKey != null &&
                        PointsAt(constraint.ForeignKey, tableName))
                    {
                        yield return (childTableName, childTable, constraint.ForeignKey);
                    }
                }
            }
        }
    }

    private static bool PointsAt(DefinitionForeignKey fk, string tableName) =>
        fk.ForeignTable.Equals(tableName, StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Applies ON UPDATE actions after a row's referenced columns change.
    /// </summary>
    /// <remarks>
    /// Nothing used to call this path at all: HandleCascadingActions was only ever invoked from
    /// DELETE, with isDelete: true. <see cref="DefinitionForeignKey.OnUpdate"/> was parsed, stored
    /// and read - and unreachable, so every ON UPDATE action silently did nothing and updating a
    /// referenced key left orphans behind.
    ///
    /// CASCADE means something different here than it does for a delete: the child's key is
    /// rewritten to the new value rather than the child being removed.
    /// </remarks>
    private void HandleReferentialUpdate(string tableName, WitSqlRow oldRow, WitSqlRow newRow)
    {
        var parentTable = m_context.Database.GetTable(tableName);
        if (parentTable == null)
            return;

        var pkColumns = GetPrimaryKeyColumns(parentTable);
        if (pkColumns == null)
            return;

        var parentRowId = TryGetRowId(oldRow);
        var allTableNames = GetAllTableNames().ToList();

        foreach (var (childTableName, childTable, fk) in FindReferencingForeignKeys(tableName, allTableNames))
        {
            var referencedColumns = fk.ForeignColumns is { Count: > 0 } ? fk.ForeignColumns : pkColumns;
            if (referencedColumns.Count != fk.Columns.Count)
                continue;

            var oldValues = referencedColumns.Select(c => oldRow[c]).ToArray();
            var newValues = referencedColumns.Select(c => newRow[c]).ToArray();

            // Only a change to the referenced columns concerns a foreign key. An UPDATE that leaves
            // them alone must not disturb children.
            if (!ReferencedValuesChanged(oldValues, newValues))
                continue;

            var excludeRowId = childTableName.Equals(tableName, StringComparison.OrdinalIgnoreCase)
                ? parentRowId
                : null;

            ApplyUpdateAction(childTableName, childTable, fk, oldValues, newValues, excludeRowId);
        }
    }

    private static bool ReferencedValuesChanged(WitSqlValue[] oldValues, WitSqlValue[] newValues)
    {
        for (int i = 0; i < oldValues.Length; i++)
        {
            if (oldValues[i].IsNull != newValues[i].IsNull)
                return true;

            if (!oldValues[i].IsNull && oldValues[i].CompareTo(newValues[i]) != 0)
                return true;
        }

        return false;
    }

    private void ApplyUpdateAction(
        string childTableName,
        DefinitionTable childTable,
        DefinitionForeignKey fk,
        WitSqlValue[] oldValues,
        WitSqlValue[] newValues,
        long? excludeRowId)
    {
        if (oldValues.All(v => v.IsNull))
            return;

        var action = fk.OnUpdate;

        if (action == ReferenceAction.NoAction || action == ReferenceAction.Restrict)
        {
            if (HasReferencingRows(childTableName, fk, oldValues, excludeRowId))
            {
                throw new InvalidOperationException(
                    $"Cannot update the referenced key of '{fk.ForeignTable}': " +
                    $"foreign key constraint on '{childTableName}' references it");
            }

            return;
        }

        var childRows = FindReferencingRows(childTableName, fk, oldValues, excludeRowId);
        if (childRows.Count == 0)
            return;

        foreach (var (rowId, oldChildRow) in childRows)
        {
            var newChildRow = action switch
            {
                ReferenceAction.Cascade => SetColumns(oldChildRow, fk.Columns, newValues),
                ReferenceAction.SetNull => SetColumnsToNull(oldChildRow, fk.Columns, childTable),
                ReferenceAction.SetDefault => SetColumnsToDefault(oldChildRow, fk.Columns, childTable),
                _ => null
            };

            if (newChildRow != null)
                m_context.Database.UpdateRow(childTableName, rowId, newChildRow.Value);
        }
    }

    /// <summary>
    /// Copies a row with the named columns replaced by the given values, positionally.
    /// </summary>
    private static WitSqlRow? SetColumns(
        WitSqlRow row,
        IReadOnlyList<string> columns,
        WitSqlValue[] values)
    {
        if (columns.Count != values.Length)
            return null;

        var names = row.ColumnNames.ToArray();
        var updated = names.Select(n => row[n]).ToArray();

        for (int i = 0; i < columns.Count; i++)
        {
            var index = Array.FindIndex(names, n => n.Equals(columns[i], StringComparison.OrdinalIgnoreCase));
            if (index < 0)
                return null;

            updated[index] = values[i];
        }

        return new WitSqlRow(updated, names);
    }

    private static List<string>? GetPrimaryKeyColumns(DefinitionTable table)
    {
        var pkColumns = table.PrimaryKey?.ToList();
        if (pkColumns is { Count: > 0 })
            return pkColumns;

        var pkCol = table.Columns.FirstOrDefault(c => c.IsPrimaryKey);
        return pkCol != null ? [pkCol.Name] : null;
    }

    /// <summary>
    /// Applies a foreign key's cascading action, matching child rows on the columns the key
    /// actually references.
    /// </summary>
    /// <remarks>
    /// The values that identify the referenced parent row are <b>not</b> the parent's primary key
    /// unless the foreign key says so. <see cref="DefinitionForeignKey.ForeignColumns"/> names them;
    /// only when it is absent does the reference fall back to the primary key.
    ///
    /// Comparing against the primary key regardless - which is what this code did - goes wrong in
    /// both directions at once as soon as a key points anywhere else, and a foreign key to a UNIQUE
    /// column is ordinary schema: a child whose referenced row still exists gets deleted, and a
    /// child whose referenced row is gone survives as an orphan.
    /// </remarks>
    private void CascadeToChild(
        string childTableName,
        DefinitionTable childTable,
        DefinitionForeignKey fk,
        WitSqlRow parentRow,
        List<string> parentPkColumns,
        bool isDelete,
        long? excludeRowId)
    {
        var referencedColumns = fk.ForeignColumns is { Count: > 0 }
            ? fk.ForeignColumns
            : parentPkColumns;

        // A key whose local column count does not line up with what it references cannot be matched
        // safely. Skipping is the honest answer; guessing positionally is the defect being fixed.
        if (referencedColumns.Count != fk.Columns.Count)
            return;

        var referencedValues = referencedColumns.Select(column => parentRow[column]).ToArray();

        if (referencedValues.All(value => value.IsNull))
            return;

        ApplyCascadingAction(childTableName, childTable, fk, parentPkColumns, referencedValues, isDelete, excludeRowId);
    }

    /// <summary>
    /// Gets all table names in the database.
    /// </summary>
    private IEnumerable<string> GetAllTableNames()
    {
        // We need to get all tables from the database
        // Use INFORMATION_SCHEMA or iterate through known tables
        if (m_context.Database is Engine.WitSqlEngine engine)
        {
            return engine.GetAllTableNames();
        }
        
        return [];
    }

    /// <summary>
    /// Applies the cascading action for a specific foreign key constraint.
    /// </summary>
    private void ApplyCascadingAction(
        string childTableName,
        DefinitionTable childTable,
        DefinitionForeignKey fk,
        List<string> parentPkColumns,
        WitSqlValue[] referencedValues,
        bool isDelete,
        long? excludeRowId)
    {
        // Determine which action to apply
        var action = isDelete ? fk.OnDelete : fk.OnUpdate;

        // NoAction and Restrict don't cascade - they just prevent the operation
        // For NoAction/Restrict, we should check if there are referencing rows and throw an error
        if (action == ReferenceAction.NoAction || action == ReferenceAction.Restrict)
        {
            // Check if there are any child rows referencing this parent
            if (HasReferencingRows(childTableName, fk, referencedValues, excludeRowId))
            {
                throw new InvalidOperationException(
                    $"Cannot delete row from '{parentPkColumns[0]}': foreign key constraint '{childTableName}' references it");
            }
            return;
        }

        // Find all child rows that reference the parent row
        var childRowsToProcess = FindReferencingRows(childTableName, fk, referencedValues, excludeRowId);
        
        if (childRowsToProcess.Count == 0)
            return;

        switch (action)
        {
            case ReferenceAction.Cascade:
                // Delete all referencing child rows
                foreach (var (rowId, _) in childRowsToProcess)
                {
                    // Recursively handle cascades for this child row
                    var childRow = GetRowById(childTableName, rowId);
                    if (childRow.HasValue)
                    {
                        HandleCascadingActions(childTableName, childRow.Value, isDelete: true);
                    }
                    
                    m_context.Database.DeleteRow(childTableName, rowId);
                }
                break;

            case ReferenceAction.SetNull:
                // Set the FK columns to NULL
                foreach (var (rowId, oldRow) in childRowsToProcess)
                {
                    var newRow = SetColumnsToNull(oldRow, fk.Columns, childTable);
                    m_context.Database.UpdateRow(childTableName, rowId, newRow);
                }
                break;

            case ReferenceAction.SetDefault:
                // Set the FK columns to their default values
                foreach (var (rowId, oldRow) in childRowsToProcess)
                {
                    var newRow = SetColumnsToDefault(oldRow, fk.Columns, childTable);
                    m_context.Database.UpdateRow(childTableName, rowId, newRow);
                }
                break;
        }
    }

    /// <summary>
    /// Checks if there are any rows in the child table that reference the parent row.
    /// </summary>
    private bool HasReferencingRows(
        string childTableName,
        DefinitionForeignKey fk,
        WitSqlValue[] referencedValues,
        long? excludeRowId)
    {
        var iterator = m_context.Database.CreateTableScan(childTableName);
        iterator.Open();
        
        try
        {
            while (iterator.MoveNext())
            {
                if (excludeRowId.HasValue && TryGetRowId(iterator.Current) == excludeRowId)
                    continue;

                if (RowReferencesParent(iterator.Current, fk.Columns, referencedValues))
                    return true;
            }
        }
        finally
        {
            iterator.Dispose();
        }
        
        return false;
    }

    /// <summary>
    /// Finds all rows in the child table that reference the parent row.
    /// </summary>
    private List<(long RowId, WitSqlRow Row)> FindReferencingRows(
        string childTableName,
        DefinitionForeignKey fk,
        WitSqlValue[] referencedValues,
        long? excludeRowId)
    {
        var result = new List<(long RowId, WitSqlRow Row)>();
        
        var iterator = m_context.Database.CreateTableScan(childTableName);
        iterator.Open();
        
        try
        {
            while (iterator.MoveNext())
            {
                if (excludeRowId.HasValue && TryGetRowId(iterator.Current) == excludeRowId)
                    continue;

                if (RowReferencesParent(iterator.Current, fk.Columns, referencedValues))
                {
                    var rowId = iterator.Current["_rowid"].AsInt64();
                    result.Add((rowId, iterator.Current));
                }
            }
        }
        finally
        {
            iterator.Dispose();
        }
        
        return result;
    }

    /// <summary>
    /// Checks if a child row references the parent row through the foreign key.
    /// </summary>
    private static bool RowReferencesParent(
        WitSqlRow childRow,
        IReadOnlyList<string> fkColumns,
        WitSqlValue[] referencedValues)
    {
        for (int i = 0; i < fkColumns.Count && i < referencedValues.Length; i++)
        {
            var childValue = childRow[fkColumns[i]];
            var parentValue = referencedValues[i];
            
            // NULL values don't match
            if (childValue.IsNull || parentValue.IsNull)
                return false;
            
            if (!childValue.Equals(parentValue))
                return false;
        }
        
        return true;
    }

    /// <summary>
    /// Gets a row by its row ID.
    /// </summary>
    private WitSqlRow? GetRowById(string tableName, long rowId)
    {
        var iterator = m_context.Database.CreateTableScan(tableName);
        iterator.Open();
        
        try
        {
            while (iterator.MoveNext())
            {
                if (iterator.Current["_rowid"].AsInt64() == rowId)
                    return iterator.Current;
            }
        }
        finally
        {
            iterator.Dispose();
        }
        
        return null;
    }

    /// <summary>
    /// Creates a new row with specified columns set to NULL.
    /// </summary>
    private static WitSqlRow SetColumnsToNull(WitSqlRow oldRow, IReadOnlyList<string> columnsToNull, DefinitionTable table)
    {
        var newValues = new WitSqlValue[oldRow.ColumnCount];
        var newColumns = new string[oldRow.ColumnCount];
        
        for (int i = 0; i < oldRow.ColumnCount; i++)
        {
            var colName = oldRow.GetColumnName(i);
            newColumns[i] = colName;
            
            if (columnsToNull.Any(c => c.Equals(colName, StringComparison.OrdinalIgnoreCase)))
            {
                newValues[i] = WitSqlValue.Null;
            }
            else
            {
                newValues[i] = oldRow[i];
            }
        }
        
        return new WitSqlRow(newValues, newColumns);
    }

    /// <summary>
    /// Creates a new row with specified columns set to their default values.
    /// </summary>
    private WitSqlRow SetColumnsToDefault(WitSqlRow oldRow, IReadOnlyList<string> columnsToDefault, DefinitionTable table)
    {
        var newValues = new WitSqlValue[oldRow.ColumnCount];
        var newColumns = new string[oldRow.ColumnCount];
        var evaluator = new ExpressionEvaluator(m_context);
        
        for (int i = 0; i < oldRow.ColumnCount; i++)
        {
            var colName = oldRow.GetColumnName(i);
            newColumns[i] = colName;
            
            if (columnsToDefault.Any(c => c.Equals(colName, StringComparison.OrdinalIgnoreCase)))
            {
                // Get the default value for this column from table definition
                var col = table.GetColumn(colName);
                
                if (col?.ResolveDefault() is not null)
                {
                    // Use cached expression parsing
                    var defaultExpr = col.ResolveDefault()!;
                    var defaultValue = evaluator.Evaluate(defaultExpr, oldRow);
                    newValues[i] = defaultValue;
                }
                else
                {
                    // Column found but no default value - this is an error for SET DEFAULT
                    // Fall back to NULL (SQL standard behavior when no default defined)
                    newValues[i] = WitSqlValue.Null;
                }
            }
            else
            {
                newValues[i] = oldRow[i];
            }
        }
        
        return new WitSqlRow(newValues, newColumns);
    }

    #endregion

    #region UNIQUE Constraints

    private void ValidateUniqueConstraints(DefinitionTable table, WitSqlRow row, string tableName, long? excludeRowId = null)
    {
        ValidateUniqueConstraintsWithAutoGen(table, row, tableName, null, excludeRowId);
    }

    /// <summary>
    /// Validates UNIQUE constraints, with ability to skip validation for auto-generated columns.
    /// </summary>
    private void ValidateUniqueConstraintsWithAutoGen(
        DefinitionTable table, 
        WitSqlRow row, 
        string tableName, 
        HashSet<string>? autoGeneratedPkColumns,
        long? excludeRowId = null)
    {
        var constraintSets = new List<(IReadOnlyList<string> Columns, string Description, bool CanSkip)>();

        // 1. Add column-level UNIQUE constraints (single columns)
        foreach (var col in table.Columns)
        {
            if (col.IsUnique)
            {
                bool canSkip = autoGeneratedPkColumns?.Contains(col.Name) ?? false;
                constraintSets.Add(([col.Name], $"UNIQUE constraint on {tableName}.{col.Name}", canSkip));
            }
        }

        // 2. Add PRIMARY KEY as unique constraint
        if (table.PrimaryKey != null && table.PrimaryKey.Count > 0)
        {
            bool canSkip = autoGeneratedPkColumns != null && 
                           table.PrimaryKey.All(pk => autoGeneratedPkColumns.Contains(pk));
            constraintSets.Add((table.PrimaryKey, $"PRIMARY KEY constraint on {tableName}", canSkip));
        }
        else
        {
            // Single-column PRIMARY KEY via column flags
            foreach (var col in table.Columns)
            {
                if (col.IsPrimaryKey)
                {
                    bool alreadyAdded = constraintSets.Any(cs =>
                        cs.Columns.Count == 1 &&
                        cs.Columns[0].Equals(col.Name, StringComparison.OrdinalIgnoreCase));

                    if (!alreadyAdded)
                    {
                        bool canSkip = autoGeneratedPkColumns?.Contains(col.Name) ?? false;
                        constraintSets.Add(([col.Name], $"PRIMARY KEY constraint on {tableName}.{col.Name}", canSkip));
                    }
                }
            }
        }

        // 3. Add table-level composite UNIQUE constraints
        if (table.UniqueConstraints != null)
        {
            foreach (var uniqueColumns in table.UniqueConstraints)
            {
                bool canSkip = autoGeneratedPkColumns != null && 
                               uniqueColumns.All(c => autoGeneratedPkColumns.Contains(c));
                constraintSets.Add((uniqueColumns, $"UNIQUE constraint on {tableName}({string.Join(", ", uniqueColumns)})", canSkip));
            }
        }

        if (constraintSets.Count == 0)
            return;

        // Filter out constraints that can be skipped (auto-generated values are guaranteed unique)
        // Also filter out constraints where all values are NULL
        var activeConstraints = constraintSets
            .Where(cs => !cs.CanSkip)
            .Where(cs => !cs.Columns.All(c => row[c].IsNull))
            .Select(cs => (cs.Columns, cs.Description))
            .ToList();
            
        if (activeConstraints.Count == 0)
            return;

        // Get indexes once - avoid repeated calls
        IEnumerable<DefinitionIndex>? indexes = null;
        var remainingConstraints = new List<(IReadOnlyList<string> Columns, string Description)>();
        
        foreach (var (columns, description) in activeConstraints)
        {
            var keyValues = columns.Select(c => row[c]).ToArray();
            
            // Skip if any value is NULL - NULLs don't violate UNIQUE
            if (keyValues.Any(v => v.IsNull))
                continue;
                
            bool foundViaIndex = false;
            
            // Lazy load indexes only when needed
            indexes ??= m_context.Database.GetTableIndexes(tableName).ToList();
            
            // Check if there's a unique index on these exact columns
            foreach (var index in indexes)
            {
                if (index.IsUnique && 
                    index.Columns.Count == columns.Count &&
                    index.Columns.All(ic => columns.Any(c => c.Equals(ic, StringComparison.OrdinalIgnoreCase))))
                {
                    try
                    {
                        using var seekIterator = m_context.Database.CreateIndexSeek(tableName, index.Name, keyValues);
                        seekIterator.Open();
                        
                        while (seekIterator.MoveNext())
                        {
                            var existingRowId = seekIterator.Current["_rowid"].AsInt64();
                            
                            // Skip the row being updated
                            if (excludeRowId.HasValue && existingRowId == excludeRowId.Value)
                                continue;
                            
                            // Found duplicate!
                            throw new InvalidOperationException(
                                $"UNIQUE constraint failed: {tableName}.{columns[0]} (duplicate value: {row[columns[0]].AsString()})");
                        }
                        
                        foundViaIndex = true;
                    }
                    catch (InvalidOperationException)
                    {
                        // Re-throw UNIQUE constraint violations
                        throw;
                    }
                    catch
                    {
                        // Index seek failed - fall back to scan
                        foundViaIndex = false;
                    }
                    
                    break;
                }
            }
            
            if (!foundViaIndex)
            {
                remainingConstraints.Add((columns, description));
            }
        }

        // Fall back to full scan for constraints without indexes
        if (remainingConstraints.Count == 0)
            return;

        var iterator = m_context.Database.CreateTableScan(tableName);
        iterator.Open();

        try
        {
            while (iterator.MoveNext())
            {
                var existingRow = iterator.Current;

                // Skip the row being updated (for UPDATE operations)
                if (excludeRowId.HasValue)
                {
                    var rowIdValue = existingRow["_rowid"];
                    if (!rowIdValue.IsNull && rowIdValue.AsInt64() == excludeRowId.Value)
                        continue;
                }

                // Check each remaining constraint set
                foreach (var (columns, description) in remainingConstraints)
                {
                    if (IsUniqueViolation(row, existingRow, columns))
                    {
                        throw new InvalidOperationException(
                            $"UNIQUE constraint failed: {tableName}.{columns[0]} (duplicate value: {row[columns[0]].AsString()})");
                    }
                }
            }
        }
        finally
        {
            iterator.Dispose();
        }
    }
    
    private static bool IsUniqueViolation(WitSqlRow newRow, WitSqlRow existingRow, IReadOnlyList<string> columns)
    {
        foreach (var colName in columns)
        {
            var newValue = newRow[colName];
            var existingValue = existingRow[colName];

            // NULL values don't violate UNIQUE constraint
            if (newValue.IsNull || existingValue.IsNull)
                return false;

            if (!newValue.Equals(existingValue))
                return false;
        }

        return true; // All columns match - it's a duplicate
    }

    #endregion

    #region CHECK Constraints

    /// <summary>
    /// Rounds every value to the scale its column declared, returning the row to be written.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>DECIMAL(5,2)</c> means two decimal places, and PostgreSQL stores 123.46 when given 123.456 -
    /// it coerces rather than refusing, and the value in the database afterwards is the rounded one.
    /// Checking the range and then storing the original would leave the declared scale as a thing the
    /// catalog says and the data ignores, which is the shape this phase exists to remove.
    /// </para>
    /// <para>
    /// The row is only rebuilt when something actually changes, so the ordinary write - every column
    /// without a declared scale, and every value already at it - allocates nothing.
    /// </para>
    /// </remarks>
    private static WitSqlRow CoerceDeclaredScale(DefinitionTable table, WitSqlRow row)
    {
        WitSqlValue[]? coerced = null;

        for (var i = 0; i < row.ColumnCount; i++)
        {
            var name = row.GetColumnName(i);

            var column = table.Columns.FirstOrDefault(
                c => string.Equals(c.Name, name, StringComparison.OrdinalIgnoreCase));

            if (column?.Scale is not { } scale || scale < 0)
                continue;

            var value = row[i];
            if (value.IsNull || !IsNumeric(value))
                continue;

            var original = value.AsDecimal();
            var rounded = Math.Round(original, scale, MidpointRounding.AwayFromZero);

            if (rounded == original)
                continue;

            coerced ??= row.Values.ToArray();
            coerced[i] = WitSqlValue.FromDecimal(rounded);
        }

        return coerced == null ? row : new WitSqlRow(coerced, row.ColumnNames.ToArray());
    }

    /// <summary>
    /// Enforces the sizes a column was declared with - <c>VARCHAR(n)</c>, <c>CHAR(n)</c> and the
    /// precision and scale of <c>DECIMAL(p,s)</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Added 2026-07-31. Until then these were declared, parsed, and then absent in every dimension:
    /// not recorded in the catalog, not reported by <c>INFORMATION_SCHEMA</c>, not enforced. <b>This is
    /// the behaviour change of phase 7</b> - data that used to be accepted is now refused, which is why
    /// it belongs in a major release.
    /// </para>
    /// <para>
    /// <b>The rules follow PostgreSQL and SQL Server rather than being stricter than them</b>, because
    /// drop-in is the target:
    /// </para>
    /// <list type="bullet">
    /// <item>A string longer than its declared length is <b>refused</b>, not truncated. Silently losing
    /// the end of a value is the one outcome nobody can want.</item>
    /// <item>A number with more decimals than its scale is <b>rounded</b> to that scale, exactly as
    /// PostgreSQL does - <c>123.456</c> into <c>DECIMAL(5,2)</c> is 123.46, not an error.</item>
    /// <item>A number whose integer part does not fit in <c>precision - scale</c> digits is
    /// <b>refused</b>: that is overflow, and there is no rounding that saves it.</item>
    /// </list>
    /// <para>
    /// NULL is skipped, as every other constraint here does.
    /// </para>
    /// </remarks>
    private static void ValidateDeclaredSizes(DefinitionTable table, WitSqlRow row, string tableName)
    {
        foreach (var col in table.Columns)
        {
            if (col.MaxLength == null && col.Precision == null)
                continue;

            var value = row[col.Name];
            if (value.IsNull)
                continue;

            if (col.MaxLength is { } maxLength && maxLength > 0 && IsTextual(value))
            {
                var text = value.AsString();

                if (text.Length > maxLength)
                {
                    throw new InvalidOperationException(
                        $"Value too long for column '{tableName}.{col.Name}': {text.Length} characters, "
                        + $"declared {maxLength}.");
                }
            }

            if (col.Precision is { } precision && precision > 0 && IsNumeric(value))
            {
                var scale = col.Scale ?? 0;
                var rounded = Math.Round(value.AsDecimal(), scale, MidpointRounding.AwayFromZero);

                var integerDigits = IntegerDigitCount(rounded);

                if (integerDigits > precision - scale)
                {
                    throw new InvalidOperationException(
                        $"Numeric value out of range for column '{tableName}.{col.Name}': "
                        + $"{rounded} does not fit DECIMAL({precision},{scale}).");
                }
            }
        }
    }

    private static bool IsTextual(WitSqlValue value) =>
        value.Type is WitSqlType.Text;

    private static bool IsNumeric(WitSqlValue value) =>
        value.Type is WitSqlType.Integer or WitSqlType.Real or WitSqlType.Decimal;

    /// <summary>Digits before the decimal point, with zero counting as one digit.</summary>
    private static int IntegerDigitCount(decimal value)
    {
        var integerPart = Math.Truncate(Math.Abs(value));

        return integerPart < 1 ? 1 : (int)Math.Floor(Math.Log10((double)integerPart)) + 1;
    }

    private void ValidateCheckConstraints(DefinitionTable table, WitSqlRow row, string tableName)
    {
        var evaluator = new ExpressionEvaluator(m_context);

        // Validate column-level CHECK constraints
        foreach (var col in table.Columns)
        {
            if (col.ResolveCheck() is null)
                continue;

            // Skip CHECK if the column value is NULL (SQL standard behavior)
            var columnValue = row[col.Name];
            if (columnValue.IsNull)
                continue;

            // Use cached expression parsing
            var checkExpr = col.ResolveCheck()!;
            var result = evaluator.Evaluate(checkExpr, row);

            // Skip if result is NULL
            if (result.IsNull)
                continue;

            if (!result.AsBool())
            {
                throw new InvalidOperationException($"CHECK constraint failed for column {tableName}.{col.Name}");
            }
        }

        // Validate table-level CHECK constraints
        if (table.ResolveChecks().Count > 0)
        {
            foreach (var checkExpr in table.ResolveChecks())
            {
                var result = evaluator.Evaluate(checkExpr, row);

                // Skip if result is NULL
                if (result.IsNull)
                    continue;

                if (!result.AsBool())
                {
                    throw new InvalidOperationException($"CHECK constraint failed for table {tableName}");
                }
            }
        }
    }

    #endregion

    #region FOREIGN KEY Constraints

    private void ValidateForeignKeyConstraints(DefinitionTable table, WitSqlRow row, string tableName)
    {
        // Validate column-level FK constraints
        foreach (var col in table.Columns)
        {
            if (col.ForeignKey != null)
            {
                ValidateForeignKeyReference(col.ForeignKey, row, tableName);
            }
        }

        // Validate table-level FK constraints
        if (table.ForeignKeys != null)
        {
            foreach (var fk in table.ForeignKeys)
            {
                ValidateForeignKeyReference(fk, row, tableName);
            }
        }
    }

    private void ValidateForeignKeyReference(DefinitionForeignKey fk, WitSqlRow row, string tableName)
    {
        var foreignTable = m_context.Database.GetTable(fk.ForeignTable)
            ?? throw new InvalidOperationException($"Referenced table '{fk.ForeignTable}' not found");

        // Get local values for FK columns
        var localValues = new List<WitSqlValue>();
        bool allNull = true;

        foreach (var colName in fk.Columns)
        {
            var val = row[colName];
            localValues.Add(val);
            if (!val.IsNull) allNull = false;
        }

        // NULL values don't violate FK constraint
        if (allNull)
            return;

        // Determine foreign columns to check
        var foreignColumns = fk.ForeignColumns?.ToList()
            ?? foreignTable.PrimaryKey?.ToList()
            ?? throw new InvalidOperationException(
                $"Cannot validate FK constraint: referenced table '{fk.ForeignTable}' has no primary key");

        // Scan foreign table to find matching row
        var iterator = m_context.Database.CreateTableScan(fk.ForeignTable);
        iterator.Open();
        bool found = false;

        try
        {
            while (iterator.MoveNext())
            {
                var foreignRow = iterator.Current;
                bool matches = true;

                for (int i = 0; i < localValues.Count && i < foreignColumns.Count; i++)
                {
                    var localVal = localValues[i];
                    var foreignVal = foreignRow[foreignColumns[i]];

                    if (localVal.IsNull || foreignVal.IsNull || !localVal.Equals(foreignVal))
                    {
                        matches = false;
                        break;
                    }
                }

                if (matches)
                {
                    found = true;
                    break;
                }
            }
        }
        finally
        {
            iterator.Dispose();
        }

        if (!found)
        {
            var valuesStr = string.Join(", ", localValues.Select(v => v.AsString()));
            throw new InvalidOperationException(
                $"FOREIGN KEY constraint failed: {tableName} -> {fk.ForeignTable} (values: {valuesStr})");
        }
    }

    #endregion

    #region Named Constraints (via ALTER TABLE ADD CONSTRAINT)

    /// <summary>
    /// Validates named constraints added via ALTER TABLE ADD CONSTRAINT.
    /// </summary>
    private void ValidateNamedConstraints(DefinitionTable table, WitSqlRow row, string tableName, long? excludeRowId = null)
    {
        if (table.NamedConstraints == null || table.NamedConstraints.Count == 0)
            return;

        var evaluator = new ExpressionEvaluator(m_context);

        foreach (var constraint in table.NamedConstraints)
        {
            switch (constraint.Type)
            {
                case ConstraintType.Check:
                    ValidateNamedCheckConstraint(constraint, row, tableName, evaluator);
                    break;

                case ConstraintType.Unique:
                    ValidateNamedUniqueConstraint(constraint, row, tableName, excludeRowId);
                    break;

                case ConstraintType.ForeignKey:
                    ValidateNamedForeignKeyConstraint(constraint, row, tableName);
                    break;

                // PRIMARY KEY constraints are not added via ALTER TABLE
            }
        }
    }

    private void ValidateNamedCheckConstraint(
        DefinitionNamedConstraint constraint, 
        WitSqlRow row, 
        string tableName,
        ExpressionEvaluator evaluator)
    {
        if (constraint.ResolveCheck() is null)
            return;

        // Use cached expression parsing
        var checkExpr = constraint.ResolveCheck()!;
        var result = evaluator.Evaluate(checkExpr, row);

        // Skip if result is NULL (SQL standard: NULL is not FALSE)
        if (result.IsNull)
            return;

        if (!result.AsBool())
        {
            throw new InvalidOperationException(
                $"CHECK constraint '{constraint.Name}' failed for table {tableName}");
        }
    }

    private void ValidateNamedUniqueConstraint(
        DefinitionNamedConstraint constraint, 
        WitSqlRow row, 
        string tableName,
        long? excludeRowId)
    {
        if (constraint.Columns == null || constraint.Columns.Count == 0)
            return;

        // Check if all values are NULL - NULLs don't violate UNIQUE
        bool allNull = constraint.Columns.All(col => row[col].IsNull);
        if (allNull)
            return;

        // Scan existing rows to check for duplicates
        var iterator = m_context.Database.CreateTableScan(tableName);
        iterator.Open();

        try
        {
            while (iterator.MoveNext())
            {
                var existingRow = iterator.Current;

                // Skip the row being updated
                if (excludeRowId.HasValue)
                {
                    var rowIdValue = existingRow["_rowid"];
                    if (!rowIdValue.IsNull && rowIdValue.AsInt64() == excludeRowId.Value)
                        continue;
                }

                if (IsUniqueViolation(row, existingRow, constraint.Columns))
                {
                    throw new InvalidOperationException(
                        $"UNIQUE constraint '{constraint.Name}' failed for table {tableName}");
                }
            }
        }
        finally
        {
            iterator.Dispose();
        }
    }

    private void ValidateNamedForeignKeyConstraint(
        DefinitionNamedConstraint constraint, 
        WitSqlRow row, 
        string tableName)
    {
        if (constraint.ForeignKey == null)
            return;

        ValidateForeignKeyReference(constraint.ForeignKey, row, tableName);
    }

    #endregion

    #region Declaration-time validation

    /// <summary>
    /// Refuses a DDL statement whose stored expressions name a function the engine cannot evaluate.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Measured 2026-08-01: a <c>CHECK</c>, a computed column, an index expression and a view all
    /// accepted <c>NoSuchFunc(V)</c> at declaration. Two threw at first use and the computed column
    /// answered NULL, which is worse. Phase 7's rule is accepted, enforced, or refused, and the
    /// declaration is the last moment the caller still has the statement that is wrong in their hand
    /// and the table has no rows depending on it.
    /// </para>
    /// <para>
    /// Asked of the <b>whole statement</b> rather than of each clause, so a place a function can be
    /// written that nobody listed here is still covered - a column <c>CHECK</c>, a table
    /// <c>CHECK</c>, a computed column and a <c>DEFAULT</c> are four such places in
    /// <c>CREATE TABLE</c> alone, and <c>ALTER TABLE</c> reaches three of them again. The walk stops
    /// at a nested statement, so a <c>CREATE TABLE … AS SELECT</c> is not dragged in.
    /// </para>
    /// <para>
    /// <b>Views are deliberately not covered.</b> A view body is a query, and a query naming an
    /// unknown function already fails loudly when it is selected from - there is no silent answer to
    /// close there, and validating an arbitrary query body at declaration is a larger surface than
    /// this finding asked for. Stated so the gap is a decision and not an oversight.
    /// </para>
    /// </remarks>
    private static void RefuseUnknownFunctions(WitSqlStatement statement, string objectName)
    {
        var unknown = ExpressionFunctions.FirstUnknownFunction(statement);

        if (unknown == null)
            return;

        throw new NotSupportedException(
            $"'{objectName}' cannot be declared because it uses the function {unknown}(), which this "
            + "engine does not have. A function named in a CHECK, a computed column, a DEFAULT or an "
            + "index expression is evaluated for every row, so it has to exist before the schema can "
            + "depend on it.");
    }

    #endregion
}
