using System.Reflection;
using Microsoft.EntityFrameworkCore;

namespace OutWit.Database.EntityFramework.Specification.Tests;

/// <summary>
/// EF Core's own meta-test: it walks the specification assemblies and reports every test base a
/// provider has not implemented. That report is the authoritative statement of what "drop-in EF Core
/// provider" still means for WitDatabase - written by EF Core rather than by us.
///
/// The list below is the baseline it was first run against, which makes the test do two jobs. It
/// fails when an EF Core upgrade introduces a suite nobody has looked at, and its length is the
/// conformance ledger: implementing a suite means deleting its line from here, the same way fixing a
/// confirmed defect means deleting the Ignore marker that recorded it. (Spelled without brackets on
/// purpose - the marker count is taken by grepping for the literal attribute, and prose about it
/// must not inflate the total.)
///
/// Held as names rather than typeof() because the two target frameworks do not offer the same
/// suites - EF Core 9 reports 236 and EF Core 10 reports 323, overlapping but neither
/// containing the other. One list covers both: a name absent from the running version resolves to
/// nothing and is skipped, while a suite present but unlisted still fails the test, which is the
/// direction that matters.
///
/// Baseline taken 2026-07-28 against EF Core 9.0.6 and 10.0.2. It started at 325 suites in
/// the union and stands at 317: a line goes when its suite is wired, whether or not the suite
/// then passes - the ledger counts what has been looked at.
/// </summary>
public class WitComplianceTest : RelationalComplianceTestBase
{
    private static readonly string[] BaselineTestBases =
    [
        "Microsoft.EntityFrameworkCore.AdHocManyToManyQueryTestBase",
        "Microsoft.EntityFrameworkCore.AdHocMiscellaneousQueryTestBase",
        "Microsoft.EntityFrameworkCore.ApiConsistencyTestBase`1",
        "Microsoft.EntityFrameworkCore.BadDataJsonDeserializationTestBase",
        "Microsoft.EntityFrameworkCore.BuiltInDataTypesTestBase`1",
        "Microsoft.EntityFrameworkCore.BulkUpdates.BulkUpdatesTestBase`1",
        "Microsoft.EntityFrameworkCore.BulkUpdates.ComplexTypeBulkUpdatesRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.BulkUpdates.ComplexTypeBulkUpdatesTestBase`1",
        "Microsoft.EntityFrameworkCore.BulkUpdates.FiltersInheritanceBulkUpdatesRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.BulkUpdates.FiltersInheritanceBulkUpdatesTestBase`1",
        "Microsoft.EntityFrameworkCore.BulkUpdates.InheritanceBulkUpdatesRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.BulkUpdates.InheritanceBulkUpdatesTestBase`1",
        "Microsoft.EntityFrameworkCore.BulkUpdates.NonSharedModelBulkUpdatesRelationalTestBase",
        "Microsoft.EntityFrameworkCore.BulkUpdates.NonSharedModelBulkUpdatesTestBase",
        "Microsoft.EntityFrameworkCore.BulkUpdates.NorthwindBulkUpdatesRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.BulkUpdates.NorthwindBulkUpdatesTestBase`1",
        "Microsoft.EntityFrameworkCore.BulkUpdates.TPCFiltersInheritanceBulkUpdatesTestBase`1",
        "Microsoft.EntityFrameworkCore.BulkUpdates.TPCInheritanceBulkUpdatesTestBase`1",
        "Microsoft.EntityFrameworkCore.BulkUpdates.TPHInheritanceBulkUpdatesTestBase`1",
        "Microsoft.EntityFrameworkCore.BulkUpdates.TPTFiltersInheritanceBulkUpdatesTestBase`1",
        "Microsoft.EntityFrameworkCore.BulkUpdates.TPTInheritanceBulkUpdatesTestBase`1",
        "Microsoft.EntityFrameworkCore.CommandInterceptionTestBase",
        "Microsoft.EntityFrameworkCore.ComplexTypesTrackingRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.ComplexTypesTrackingTestBase`1",
        "Microsoft.EntityFrameworkCore.ConcurrencyDetectorDisabledRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.ConcurrencyDetectorDisabledTestBase`1",
        "Microsoft.EntityFrameworkCore.ConcurrencyDetectorEnabledRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.ConcurrencyDetectorEnabledTestBase`1",
        "Microsoft.EntityFrameworkCore.ConcurrencyDetectorTestBase`1",
        "Microsoft.EntityFrameworkCore.ConferencePlannerTestBase`1",
        "Microsoft.EntityFrameworkCore.ConnectionInterceptionTestBase",
        "Microsoft.EntityFrameworkCore.ConvertToProviderTypesTestBase`1",
        "Microsoft.EntityFrameworkCore.CustomConvertersTestBase`1",
        "Microsoft.EntityFrameworkCore.DataAnnotationRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.DataAnnotationTestBase`1",
        "Microsoft.EntityFrameworkCore.DataBindingTestBase`1",
        "Microsoft.EntityFrameworkCore.DesignTimeTestBase`1",
        "Microsoft.EntityFrameworkCore.EntityFrameworkServiceCollectionExtensionsTestBase",
        "Microsoft.EntityFrameworkCore.EntitySplittingTestBase",
        "Microsoft.EntityFrameworkCore.FieldsOnlyLoadTestBase`1",
        "Microsoft.EntityFrameworkCore.GraphUpdatesTestBase`1",
        "Microsoft.EntityFrameworkCore.InterceptionTestBase",
        "Microsoft.EntityFrameworkCore.JsonTypesRelationalTestBase",
        "Microsoft.EntityFrameworkCore.JsonTypesTestBase",
        "Microsoft.EntityFrameworkCore.KeysWithConvertersTestBase`1",
        "Microsoft.EntityFrameworkCore.LazyLoadProxyRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.LazyLoadProxyTestBase`1",
        "Microsoft.EntityFrameworkCore.LoggingRelationalTestBase`2",
        "Microsoft.EntityFrameworkCore.LoggingTestBase",
        "Microsoft.EntityFrameworkCore.ManyToManyFieldsLoadTestBase`1",
        "Microsoft.EntityFrameworkCore.ManyToManyLoadTestBase`1",
        "Microsoft.EntityFrameworkCore.ManyToManyTrackingRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.ManyToManyTrackingTestBase`1",
        "Microsoft.EntityFrameworkCore.MaterializationInterceptionTestBase`1",
        "Microsoft.EntityFrameworkCore.Migrations.MigrationsInfrastructureTestBase`1",
        "Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGeneratorTestBase",
        "Microsoft.EntityFrameworkCore.Migrations.MigrationsTestBase`1",
        "Microsoft.EntityFrameworkCore.ModelBuilding.ModelBuilderTest+ComplexCollectionTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.ModelBuilderTest+ComplexTypeTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.ModelBuilderTest+InheritanceTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.ModelBuilderTest+ManyToManyTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.ModelBuilderTest+ManyToOneTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.ModelBuilderTest+ModelBuilderTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.ModelBuilderTest+NonRelationshipTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.ModelBuilderTest+OneToManyTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.ModelBuilderTest+OneToOneTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.ModelBuilderTest+OwnedTypesTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.RelationalModelBuilderTest+RelationalComplexCollectionTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.RelationalModelBuilderTest+RelationalComplexTypeTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.RelationalModelBuilderTest+RelationalInheritanceTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.RelationalModelBuilderTest+RelationalManyToManyTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.RelationalModelBuilderTest+RelationalManyToOneTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.RelationalModelBuilderTest+RelationalNonRelationshipTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.RelationalModelBuilderTest+RelationalOneToManyTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.RelationalModelBuilderTest+RelationalOneToOneTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding.RelationalModelBuilderTest+RelationalOwnedTypesTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding101RelationalTestBase",
        "Microsoft.EntityFrameworkCore.ModelBuilding101TestBase",
        "Microsoft.EntityFrameworkCore.MonsterFixupTestBase`1",
        "Microsoft.EntityFrameworkCore.MusicStoreTestBase`1",
        "Microsoft.EntityFrameworkCore.OptimisticConcurrencyRelationalTestBase`2",
        "Microsoft.EntityFrameworkCore.OptimisticConcurrencyTestBase`2",
        "Microsoft.EntityFrameworkCore.OverzealousInitializationTestBase`1",
        "Microsoft.EntityFrameworkCore.OwnedEntityQueryTestBase",
        "Microsoft.EntityFrameworkCore.PropertyValuesRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.ProxyGraphUpdatesTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.AdHocAdvancedMappingsQueryRelationalTestBase",
        "Microsoft.EntityFrameworkCore.Query.AdHocAdvancedMappingsQueryTestBase",
        "Microsoft.EntityFrameworkCore.Query.AdHocComplexTypeQueryRelationalTestBase",
        "Microsoft.EntityFrameworkCore.Query.AdHocComplexTypeQueryTestBase",
        "Microsoft.EntityFrameworkCore.Query.AdHocJsonQueryRelationalTestBase",
        "Microsoft.EntityFrameworkCore.Query.AdHocJsonQueryTestBase",
        "Microsoft.EntityFrameworkCore.Query.AdHocManyToManyQueryRelationalTestBase",
        "Microsoft.EntityFrameworkCore.Query.AdHocMiscellaneousQueryRelationalTestBase",
        "Microsoft.EntityFrameworkCore.Query.AdHocNavigationsQueryRelationalTestBase",
        "Microsoft.EntityFrameworkCore.Query.AdHocNavigationsQueryTestBase",
        "Microsoft.EntityFrameworkCore.Query.AdHocPrecompiledQueryRelationalTestBase",
        "Microsoft.EntityFrameworkCore.Query.AdHocQueryFiltersQueryRelationalTestBase",
        "Microsoft.EntityFrameworkCore.Query.AdHocQueryFiltersQueryTestBase",
        "Microsoft.EntityFrameworkCore.Query.AdHocQuerySplittingQueryTestBase",
        "Microsoft.EntityFrameworkCore.Query.Associations.AssociationsBulkUpdateTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.AssociationsCollectionTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.AssociationsMiscellaneousTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.AssociationsPrimitiveCollectionTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.AssociationsProjectionTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.AssociationsSetOperationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.AssociationsStructuralEqualityTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexJson.ComplexJsonBulkUpdateRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexJson.ComplexJsonCollectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexJson.ComplexJsonMiscellaneousRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexJson.ComplexJsonPrimitiveCollectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexJson.ComplexJsonProjectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexJson.ComplexJsonSetOperationsRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexJson.ComplexJsonStructuralEqualityRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexProperties.ComplexPropertiesBulkUpdateTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexProperties.ComplexPropertiesCollectionTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexProperties.ComplexPropertiesMiscellaneousTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexProperties.ComplexPropertiesPrimitiveCollectionTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexProperties.ComplexPropertiesProjectionTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexProperties.ComplexPropertiesSetOperationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexProperties.ComplexPropertiesStructuralEqualityTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexTableSplitting.ComplexTableSplittingBulkUpdateRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexTableSplitting.ComplexTableSplittingMiscellaneousRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexTableSplitting.ComplexTableSplittingPrimitiveCollectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexTableSplitting.ComplexTableSplittingProjectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.ComplexTableSplitting.ComplexTableSplittingStructuralEqualityRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.Navigations.NavigationsCollectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.Navigations.NavigationsCollectionTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.Navigations.NavigationsIncludeRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.Navigations.NavigationsIncludeTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.Navigations.NavigationsMiscellaneousRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.Navigations.NavigationsMiscellaneousTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.Navigations.NavigationsPrimitiveCollectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.Navigations.NavigationsPrimitiveCollectionTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.Navigations.NavigationsProjectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.Navigations.NavigationsProjectionTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.Navigations.NavigationsSetOperationsRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.Navigations.NavigationsSetOperationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.Navigations.NavigationsStructuralEqualityRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.Navigations.NavigationsStructuralEqualityTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedJson.OwnedJsonBulkUpdateRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedJson.OwnedJsonCollectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedJson.OwnedJsonMiscellaneousRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedJson.OwnedJsonPrimitiveCollectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedJson.OwnedJsonProjectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedJson.OwnedJsonStructuralEqualityRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedNavigations.OwnedNavigationsCollectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedNavigations.OwnedNavigationsCollectionTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedNavigations.OwnedNavigationsMiscellaneousRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedNavigations.OwnedNavigationsMiscellaneousTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedNavigations.OwnedNavigationsPrimitiveCollectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedNavigations.OwnedNavigationsPrimitiveCollectionTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedNavigations.OwnedNavigationsProjectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedNavigations.OwnedNavigationsProjectionTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedNavigations.OwnedNavigationsSetOperationsRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedNavigations.OwnedNavigationsSetOperationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedNavigations.OwnedNavigationsStructuralEqualityRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedNavigations.OwnedNavigationsStructuralEqualityTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedTableSplitting.OwnedTableSplittingMiscellaneousRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedTableSplitting.OwnedTableSplittingPrimitiveCollectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedTableSplitting.OwnedTableSplittingProjectionRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Associations.OwnedTableSplitting.OwnedTableSplittingStructuralEqualityRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ComplexNavigationsCollectionsQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ComplexNavigationsCollectionsQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ComplexNavigationsCollectionsSharedTypeQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ComplexNavigationsCollectionsSharedTypeQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ComplexNavigationsCollectionsSplitQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ComplexNavigationsCollectionsSplitSharedTypeQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ComplexNavigationsQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ComplexNavigationsQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ComplexNavigationsSharedTypeQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ComplexNavigationsSharedTypeQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ComplexTypeQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ComplexTypeQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.CompositeKeysQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.CompositeKeysQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.CompositeKeysSplitQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Ef6GroupByTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.EntitySplittingQueryTestBase",
        "Microsoft.EntityFrameworkCore.Query.FilteredQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.FiltersInheritanceQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.FromSqlQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.FromSqlSprocQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.FunkyDataQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.GearsOfWarFromSqlQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.GearsOfWarQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.GearsOfWarQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.IncludeOneToOneTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.InheritanceQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.InheritanceRelationshipsQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.InheritanceRelationshipsQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.JsonQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.JsonQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ManyToManyNoTrackingQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ManyToManyNoTrackingQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ManyToManyQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ManyToManyQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.MappingQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NonSharedPrimitiveCollectionsQueryRelationalTestBase",
        "Microsoft.EntityFrameworkCore.Query.NonSharedPrimitiveCollectionsQueryTestBase",
        "Microsoft.EntityFrameworkCore.Query.NorthwindAggregateOperatorsQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindAggregateOperatorsQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindAsNoTrackingQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindAsTrackingQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindChangeTrackingQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindCompiledQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindDbFunctionsQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindDbFunctionsQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindEFPropertyIncludeQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindFunctionsQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindFunctionsQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindGroupByQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindGroupByQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindIncludeNoTrackingQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindIncludeQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindIncludeQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindJoinQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindJoinQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindKeylessEntitiesQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindKeylessEntitiesQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindMiscellaneousQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindMiscellaneousQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindNavigationsQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindNavigationsQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindQueryFiltersQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindQueryTaggingQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindSelectQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindSelectQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindSetOperationsQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindSetOperationsQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindSplitIncludeNoTrackingQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindSplitIncludeQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindSqlQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindStringIncludeQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindWhereQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NorthwindWhereQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.NullSemanticsQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.OperatorsProceduralQueryTestBase",
        "Microsoft.EntityFrameworkCore.Query.OperatorsQueryTestBase",
        "Microsoft.EntityFrameworkCore.Query.OptionalDependentQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.OwnedEntityQueryRelationalTestBase",
        "Microsoft.EntityFrameworkCore.Query.OwnedQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.OwnedQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.PrecompiledQueryRelationalTestBase",
        "Microsoft.EntityFrameworkCore.Query.PrecompiledSqlPregenerationQueryRelationalTestBase",
        "Microsoft.EntityFrameworkCore.Query.PrimitiveCollectionsQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.PrimitiveCollectionsQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.QueryFilterFuncletizationTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.QueryNoClientEvalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.QueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.SharedTypeQueryRelationalTestBase",
        "Microsoft.EntityFrameworkCore.Query.SpatialQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.SpatialQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.SqlExecutorTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.SqlQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.TPCFiltersInheritanceQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.TPCGearsOfWarQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.TPCInheritanceQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.TPCManyToManyNoTrackingQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.TPCManyToManyQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.TPCRelationshipsQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.TPHInheritanceQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.TPTFiltersInheritanceQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.TPTGearsOfWarQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.TPTInheritanceQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.TPTManyToManyNoTrackingQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.TPTManyToManyQueryRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.TPTRelationshipsQueryTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.ToSqlQueryTestBase",
        "Microsoft.EntityFrameworkCore.Query.Translations.ByteArrayTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.EnumTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.GuidTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.MathTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.MiscellaneousTranslationsRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.MiscellaneousTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.Operators.ArithmeticOperatorTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.Operators.BitwiseOperatorTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.Operators.ComparisonOperatorTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.Operators.LogicalOperatorTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.Operators.MiscellaneousOperatorTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.StringTranslationsRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.StringTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.Temporal.DateOnlyTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.Temporal.DateTimeOffsetTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.Temporal.DateTimeTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.Temporal.TimeOnlyTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.Translations.Temporal.TimeSpanTranslationsTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.UdfDbFunctionTestBase`1",
        "Microsoft.EntityFrameworkCore.Query.WarningsTestBase`1",
        "Microsoft.EntityFrameworkCore.QueryExpressionInterceptionTestBase",
        "Microsoft.EntityFrameworkCore.RelationalServiceCollectionExtensionsTestBase",
        "Microsoft.EntityFrameworkCore.SaveChangesInterceptionTestBase",
        "Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelRelationalTestBase",
        "Microsoft.EntityFrameworkCore.Scaffolding.CompiledModelTestBase",
        "Microsoft.EntityFrameworkCore.SeedingTestBase",
        "Microsoft.EntityFrameworkCore.SerializationTestBase`1",
        "Microsoft.EntityFrameworkCore.SharedTypeQueryTestBase",
        "Microsoft.EntityFrameworkCore.SingletonInterceptorsTestBase`1",
        "Microsoft.EntityFrameworkCore.SpatialTestBase`1",
        "Microsoft.EntityFrameworkCore.StoreGeneratedFixupRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.StoreGeneratedFixupTestBase`1",
        "Microsoft.EntityFrameworkCore.TPTTableSplittingTestBase",
        "Microsoft.EntityFrameworkCore.TableSplittingTestBase",
        "Microsoft.EntityFrameworkCore.TransactionInterceptionTestBase",
        "Microsoft.EntityFrameworkCore.TransactionTestBase`1",
        "Microsoft.EntityFrameworkCore.TwoDatabasesTestBase",
        "Microsoft.EntityFrameworkCore.Types.RelationalTypeTestBase`2",
        "Microsoft.EntityFrameworkCore.Types.TypeTestBase`2",
        "Microsoft.EntityFrameworkCore.Update.ComplexCollectionJsonUpdateTestBase`1",
        "Microsoft.EntityFrameworkCore.Update.JsonUpdateTestBase`1",
        "Microsoft.EntityFrameworkCore.Update.NonSharedModelUpdatesTestBase",
        "Microsoft.EntityFrameworkCore.Update.StoreValueGenerationTestBase`1",
        "Microsoft.EntityFrameworkCore.Update.StoredProcedureUpdateTestBase",
        "Microsoft.EntityFrameworkCore.Update.UpdateSqlGeneratorTestBase",
        "Microsoft.EntityFrameworkCore.Update.UpdatesRelationalTestBase`1",
        "Microsoft.EntityFrameworkCore.Update.UpdatesTestBase`1",
        "Microsoft.EntityFrameworkCore.ValueConvertersEndToEndTestBase`1",
    ];

    protected override Assembly TargetAssembly => typeof(WitComplianceTest).Assembly;

    protected override ICollection<Type> IgnoredTestBases { get; } = ResolveBaseline();

    private static HashSet<Type> ResolveBaseline()
    {
        var assemblies = new[]
        {
            typeof(ComplianceTestBase).Assembly,
            typeof(RelationalComplianceTestBase).Assembly,
        };

        return BaselineTestBases
            .Select(name => assemblies.Select(a => a.GetType(name)).FirstOrDefault(t => t != null))
            .Where(type => type != null)
            .ToHashSet()!;
    }
}
